In [4]:
import numpy as np 
import pandas as pd
import json
import time
from xgboost import XGBClassifier

In [5]:
image_DF = pd.read_csv('imjennim_output.csv', names=['name', 'objects'])
image_DF

,name,objects
0,12394053_458510841000340_1115240788_n.jpg,"['person', 'person', 'person', 'person', 'pers..."
1,10731935_1520091278281341_162288298_n.jpg,['bed']
2,10852689_312466782275263_1188918758_n.jpg,['person']
3,20225530_659931897538716_6981711296630620160_n...,['person']
4,16790289_1005605026239586_2618640718557609984_...,"['person', 'person']"
5,924274_1400198843567492_953814237_n.jpg,['person']
6,914541_178001869067937_317952802_n.jpg,['person']
7,10665397_1536240213274395_672510900_n.jpg,['person']
8,18252217_330645714065715_6423891445421178880_n...,['person']
9,12543191_489113014621226_1028111142_n.jpg,"['potted plant', 'person', 'potted plant']"
10,10632509_728866430518977_571519300_n.jpg,"['person', 'person', 'person', 'person', 'pers..."
11,10903518_1552829021670066_1126830646_n.jpg,"['bench', 'person']"
12,53036392_1199543756870430_4123373395144877902_...,"['person', 'person', 'person', 'person', 'pers..."
13,10499272_239379112939395_1562831045_n.jpg,['person']
14,11380925_1438669889773402_58711808_n.jpg,"['bowl', 'bowl', 'bowl', 'bowl', 'bowl']"
15,916335_217715501743277_1212914376_n.jpg,"['bowl', 'person', 'person', 'person']"
16,914327_1431637340419663_132040812_n.jpg,"['person', 'cell phone']"
17,11849323_1051525561525776_1078539727_n.jpg,[]
18,11203445_1423788817928102_1832779036_n.jpg,"['person', 'handbag']"
19,11312153_1681656605395858_1261770511_n.jpg,['person']
20,14156335_1011340552319511_633864276_n.jpg,['vase']
21,16906565_247711529022792_8145946363570421760_n...,"['person', 'handbag']"
22,52967952_2177183035930482_3365690233418402802_...,['person']
23,11352090_476161295880869_243663523_n.jpg,"['couch', 'vase', 'cup']"
24,11232649_1488120951408668_240753159_n.jpg,['person']
25,10254129_298979603584710_1668650592_n.jpg,[]
26,11008258_1554788144790058_1597435664_n.jpg,['person']
27,11820540_397427943786043_1809163202_n.jpg,['person']
28,28158666_340861839766186_1984768137681174528_n...,"['person', 'person', 'person', 'person']"
29,10949057_1611818405704365_1911162986_n.jpg,[]
...,...,...
674,17267631_665796483621101_3906417131037655040_n...,"['person', 'person', 'person', 'person', 'pers..."
675,12825986_595703743917605_510294440_n.jpg,['person']
676,11205649_949318375089605_1092885277_n.jpg,[]
677,44276099_333941117390858_8893244683773162131_n...,"['person', 'person']"
678,11378651_754776621312520_197421533_n.jpg,"['bus', 'person', 'bus', 'train']"
679,13129371_1179658828731217_1848096402_n.jpg,"['person', 'handbag']"
680,12724823_1095741557113152_1319453482_n.jpg,"['car', 'car', 'car', 'car']"
681,10666058_1682137865343755_1985323797_n.jpg,['person']
682,17439165_433806456961689_4191727522133573632_n...,[]
683,21107906_1931454370453494_7929095135537659904_...,"['person', 'person']"
684,17332889_268138793636178_5888573039544631296_n...,"['fork', 'knife', 'bowl', 'fork', 'bowl', 'bow..."
685,10349666_398072457001061_597198937_n.jpg,"['person', 'person']"
686,10755764_360267450798562_319081196_n.jpg,[]
687,20393936_326205094458476_5905416548364845056_n...,"['umbrella', 'umbrella', 'chair', 'umbrella', ..."
688,11230378_1478250585798490_91918828_n.jpg,"['person', 'person']"
689,51679233_2494512353909766_4485807394911596854_...,['person']
690,13256770_144903042579951_352426819_n.jpg,['person']
691,11334469_1643493572538509_1438041779_n.jpg,[]
692,11137865_1543718562515398_225441497_n.jpg,[]
693,12547498_881890845260975_517450984_n.jpg,['person']
694,14717660_1203572579731949_495163571215269888_n...,"['potted plant', 'person', 'person', 'cell pho..."
695,25023016_352652858539804_4015980969369534464_n...,"['chair', 'person', 'couch']"
696,11325100_856022621138621_1190514589_n.jpg,['person']
697,15337248_1617031028604791_3779581846229090304_...,[]
698,28751574_895715053931760_7543242815627591680_n...,['person']
699,12356604_498682103648179_553016100_n.jpg,"['person', 'person', 'person', 'person', 'pers..."
700,10914123_1587177318183976_1210999358_n.jpg,"['bowl', 'dining table', 'spoon']"
701,11931156_1469762496664784_644878222_n.jpg,['person']
702,10543535_306138039547731_185449571_n.jpg,[]
703,13745247_1776973099212196_1459999140_n.jpg,['person']

In [7]:
with open('./imjennim.json') as json_file:  
    AB_data = json.load(json_file)

In [8]:
data = [['DOW', 'day', 'month', 'year', 'time', 'timezone', 'epoch', 'num_likes', 'num_comments', 'url']]

In [9]:
for entry in AB_data['GraphImages']: 
    if entry['is_video'] == False:
        epoch = entry['taken_at_timestamp']
        text_entry = entry['edge_media_to_caption']['edges']
        text = ''
        if (len(text_entry) > 0):
            text = text_entry[0]['node']['text']
        #num_hashtags = len([i.strip("#") for i in text.split() if text.startswith("#")])
        #num_mentions = len([i.strip("@") for i in text.split() if text.startswith("@")])
        t = time.strftime("%a, %d %b %Y %H:%M:%S %Z", time.localtime(epoch))
        row = t.split(' ')
        row[0] = row[0][:len(row[0])-1]
        row.append(epoch)
        row.append(entry['edge_media_preview_like']['count'])
        row.append(entry['edge_media_to_comment']['count'])
        temp_url = entry['display_url'].split('.jpg')[0].split('/')[8] + '.jpg'
        row.append(temp_url)
        #ow.append(num_mentions)
        #row.append(num_mentions)
        data.append(row)

In [10]:
AB_df = pd.DataFrame(data, columns=['DOW', 'day', 'month', 'year', 'time', 'timezone', 'epoch', 'num_likes', 'num_comments', 'url'])
AB_df = AB_df.drop([0])

In [11]:
AB_df.head()

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,url
1,Thu,09,May,2019,09:09:50,PDT,1557418190,22752,78,p1080x1080.jpg
2,Wed,08,May,2019,09:22:29,PDT,1557332549,79623,326,p1080x1080.jpg
3,Tue,07,May,2019,11:06:28,PDT,1557252388,27926,70,57353140_699916723761015_25312804839814795_n.jpg
4,Mon,06,May,2019,18:02:32,PDT,1557190952,102329,392,57506226_329554674397956_5928846494008555580_n...
5,Sun,05,May,2019,19:32:28,PDT,1557109948,77427,231,58409176_140224253775745_6854466537499059831_n...

In [12]:
new_AB_df = AB_df.merge(image_DF, how='inner', left_on='url', right_on='name')
new_AB_df = new_AB_df.drop(columns=['url'])
text_file = open("./yolo/yolov3.txt", "r")
lines = text_file.read().split()

In [13]:
for item in lines:
    temp_item = []
    for i in new_AB_df['objects']:
        count = i.count(item)
        if count > 0:
            temp_item.append(1)
        else:
            temp_item.append(0)
    category = 'is_' + item
    new_AB_df[category] = temp_item
    
new_AB_df.head()

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,name,...,is_sink,is_refrigerator,is_book,is_clock,is_vase,is_scissors,is_teddy,is_hair,is_drier,is_toothbrush
0,Wed,01,May,2019,02:29:28,PDT,1556702968,35509,93,57618487_326781107985362_3691757228944019999_n...,...,0,0,0,0,0,0,0,0,0,0
1,Tue,23,Apr,2019,12:30:01,PDT,1556047801,30105,44,56977110_1037350036462980_4635468188186691723_...,...,0,0,0,0,0,0,0,0,0,0
2,Tue,16,Apr,2019,12:37:45,PDT,1555443465,45411,95,55894888_434910533931968_2345621896847004617_n...,...,0,0,0,0,0,0,0,1,0,0
3,Mon,15,Apr,2019,12:01:09,PDT,1555354869,115635,220,55933770_2891268344430849_2545304153764815003_...,...,0,0,0,0,0,0,0,0,0,0
4,Sun,14,Apr,2019,13:16:18,PDT,1555272978,73566,203,55807188_282399839354189_287039453160401128_n.jpg,...,0,0,0,0,0,0,0,0,0,0

In [14]:
curr_index = 1
previous_likes = np.array([])
while (curr_index <= len(new_AB_df)):
    end_index = min(len(new_AB_df) + 1, curr_index + 10)
    previous_likes = np.append(previous_likes, new_AB_df['num_likes'][curr_index:end_index].mean())
    curr_index=curr_index + 1
    
previous_likes[len(new_AB_df) - 1] = 0
new_AB_df['previous_likes'] = previous_likes

In [15]:
new_AB_df.head()

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,name,...,is_refrigerator,is_book,is_clock,is_vase,is_scissors,is_teddy,is_hair,is_drier,is_toothbrush,previous_likes
0,Wed,01,May,2019,02:29:28,PDT,1556702968,35509,93,57618487_326781107985362_3691757228944019999_n...,...,0,0,0,0,0,0,0,0,0,53268.8
1,Tue,23,Apr,2019,12:30:01,PDT,1556047801,30105,44,56977110_1037350036462980_4635468188186691723_...,...,0,0,0,0,0,0,0,0,0,55567.9
2,Tue,16,Apr,2019,12:37:45,PDT,1555443465,45411,95,55894888_434910533931968_2345621896847004617_n...,...,0,0,0,0,0,0,1,0,0,57674.7
3,Mon,15,Apr,2019,12:01:09,PDT,1555354869,115635,220,55933770_2891268344430849_2545304153764815003_...,...,0,0,0,0,0,0,0,0,0,50358.2
4,Sun,14,Apr,2019,13:16:18,PDT,1555272978,73566,203,55807188_282399839354189_287039453160401128_n.jpg,...,0,0,0,0,0,0,0,0,0,49937.3

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
avg_likes = new_AB_df['num_likes'].mean()

In [18]:
new_AB_df['datetime'] = pd.to_datetime(new_AB_df['time'])
new_AB_df['hour'] = [i.hour for i in new_AB_df['datetime']]

In [19]:
new_AB_df.shape[0]

656

In [20]:
days = pd.get_dummies(new_AB_df['DOW'])

In [21]:
months = pd.get_dummies(new_AB_df['month'])

In [22]:
new_AB_df = new_AB_df.merge(days, left_index = True, right_index = True)

In [23]:
new_AB_df = new_AB_df.dropna()
new_AB_df.loc[:, (new_AB_df != 0).any(axis=0)]

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,name,...,previous_likes,datetime,hour,Fri,Mon,Sat,Sun,Thu,Tue,Wed
0,Wed,01,May,2019,02:29:28,PDT,1556702968,35509,93,57618487_326781107985362_3691757228944019999_n...,...,53268.800000,2019-05-10 02:29:28,2,0,0,0,0,0,0,1
1,Tue,23,Apr,2019,12:30:01,PDT,1556047801,30105,44,56977110_1037350036462980_4635468188186691723_...,...,55567.900000,2019-05-10 12:30:01,12,0,0,0,0,0,1,0
2,Tue,16,Apr,2019,12:37:45,PDT,1555443465,45411,95,55894888_434910533931968_2345621896847004617_n...,...,57674.700000,2019-05-10 12:37:45,12,0,0,0,0,0,1,0
3,Mon,15,Apr,2019,12:01:09,PDT,1555354869,115635,220,55933770_2891268344430849_2545304153764815003_...,...,50358.200000,2019-05-10 12:01:09,12,0,1,0,0,0,0,0
4,Sun,14,Apr,2019,13:16:18,PDT,1555272978,73566,203,55807188_282399839354189_287039453160401128_n.jpg,...,49937.300000,2019-05-10 13:16:18,13,0,0,0,1,0,0,0
5,Sat,13,Apr,2019,10:22:09,PDT,1555176129,38921,83,55776550_169361763988902_2702176039080169972_n...,...,50970.800000,2019-05-10 10:22:09,10,0,0,1,0,0,0,0
6,Sat,13,Apr,2019,02:21:47,PDT,1555147307,36571,83,55752855_2625050234232098_843838088398943327_n...,...,52892.900000,2019-05-10 02:21:47,2,0,0,1,0,0,0,0
7,Fri,12,Apr,2019,12:34:39,PDT,1555097679,57016,133,56301935_1047236362144030_5496515970610542586_...,...,52687.300000,2019-05-10 12:34:39,12,1,0,0,0,0,0,0
8,Thu,11,Apr,2019,19:45:36,PDT,1555037136,45949,180,56923068_1294419670714671_6438082560647387399_...,...,58499.400000,2019-05-10 19:45:36,19,0,0,0,0,1,0,0
9,Fri,05,Apr,2019,10:13:38,PDT,1554484418,44275,166,54512508_697126687352202_3422361105333043800_n...,...,59377.900000,2019-05-10 10:13:38,10,1,0,0,0,0,0,0
10,Sun,31,Mar,2019,14:03:04,PDT,1554066184,45239,195,54513203_2683167691699937_6442749923738558532_...,...,60249.000000,2019-05-10 14:03:04,14,0,0,0,1,0,0,0
11,Thu,28,Mar,2019,14:14:29,PDT,1553807669,53096,202,54510953_279798862914197_6577297607972186121_n...,...,62353.100000,2019-05-10 14:14:29,14,0,0,0,0,1,0,0
12,Wed,27,Mar,2019,13:36:28,PDT,1553718988,66479,484,53270940_129048451495949_288294490845594498_n.jpg,...,61756.600000,2019-05-10 13:36:28,13,0,0,0,0,0,0,1
13,Thu,14,Mar,2019,10:01:28,PDT,1552582888,42470,181,53800834_3146961252037331_3953023831007146297_...,...,62555.300000,2019-05-10 10:01:28,10,0,0,0,0,1,0,0
14,Tue,12,Mar,2019,10:41:50,PDT,1552412510,69357,273,53093020_123713512066533_6053880981485212274_n...,...,59374.700000,2019-05-10 10:41:50,10,0,0,0,0,0,1,0
15,Mon,11,Mar,2019,09:10:43,PDT,1552320643,49256,116,53002304_302820713745040_8914217300175210287_n...,...,60802.000000,2019-05-10 09:10:43,9,0,1,0,0,0,0,0
16,Thu,07,Mar,2019,16:04:05,PST,1552003445,55792,275,53689044_558741854632878_1953248017822214991_n...,...,59423.100000,2019-05-10 16:04:05,16,0,0,0,0,1,0,0
17,Sat,02,Mar,2019,12:08:59,PST,1551557339,54960,188,52097313_298400434170775_6169665244542032990_n...,...,67029.400000,2019-05-10 12:08:59,12,0,0,1,0,0,0,0
18,Thu,28,Feb,2019,10:52:47,PST,1551379967,104070,298,53036392_1199543756870430_4123373395144877902_...,...,60477.300000,2019-05-10 10:52:47,10,0,0,0,0,1,0,0
19,Wed,27,Feb,2019,09:12:28,PST,1551287548,53060,337,51679233_2494512353909766_4485807394911596854_...,...,62590.600000,2019-05-10 09:12:28,9,0,0,0,0,0,0,1
20,Tue,26,Feb,2019,13:06:03,PST,1551215163,53950,163,52442022_452026545337216_5521586784197204350_n...,...,70021.000000,2019-05-10 13:06:03,13,0,0,0,0,0,1,0
21,Tue,26,Feb,2019,08:33:16,PST,1551198796,74137,305,51717385_763247247377515_4256838232778669031_n...,...,68581.100000,2019-05-10 08:33:16,8,0,0,0,0,0,1,0
22,Thu,21,Feb,2019,15:23:15,PST,1550791395,60514,259,51045157_2292762730774313_332680276383482140_n...,...,71880.700000,2019-05-10 15:23:15,15,0,0,0,0,1,0,0
23,Tue,12,Feb,2019,21:08:46,PST,1550034526,50457,238,51405677_241008570184059_4040248682065174999_n...,...,71187.300000,2019-05-10 21:08:46,21,0,0,0,0,0,1,0
24,Sat,09,Feb,2019,10:23:24,PST,1549736604,37551,161,51168466_359572928020448_2437528667145913500_n...,...,73870.900000,2019-05-10 10:23:24,10,0,0,1,0,0,0,0
25,Tue,05,Feb,2019,20:18:58,PST,1549426738,63529,221,50491551_365589770697407_6634568182186735780_n...,...,73688.100000,2019-05-10 20:18:58,20,0,0,0,0,0,1,0
26,Sun,03,Feb,2019,12:44:01,PST,1549226641,42003,151,49985313_392223768013562_3353461102701435109_n...,...,74056.700000,2019-05-10 12:44:01,12,0,0,0,1,0,0,0
27,Fri,01,Feb,2019,15:22:00,PST,1549063320,131023,830,50047046_756062688100476_8435742620986387308_n...,...,66906.100000,2019-05-10 15:22:00,15,1,0,0,0,0,0,0
28,Thu,31,Jan,2019,16:07:34,PST,1548979654,38549,123,50047062_1232062290282137_5690483534576559562_...,...,72048.500000,2019-05-10 16:07:34,16,0,0,0,0,1,0,0
29,Wed,30,Jan,2019,12:10:40,PST,1548879040,74193,303,50094084_251008592464373_6456451107744042356_n...,...,71128.400000,2019-05-10 12:10:40,12,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
626,Sat,28,Jul,2012,17:23:30,PDT,1343521410,5604,126,11192962_730714017039560_1007458077_n.jpg,...,2337.600000,2019-05-10 17:23:30,17,0,0,1,0,0,0,0
627,Fri,20,Jul,2012,08:53:19,PDT,1342799599,875,13,1389902_817984161625996_1809642230_n.jpg,...,2502.000000,2019-05-10 08:53:19,8,1,0,0,0,0,0,0
628,Wed,18,Jul,2012,23:10:49,PDT,1342678249,4114,76,11195587_1546463612259323_871791345_n.jpg,...,2666.600000,2019-05-10 23:10:49,23,0,0,0,0,0,0,1
629,Wed,18,Jul,2012,14:14:03,PDT,1342646043,1957,10,11176467_834227370002126_314276819_n.jpg,...,2528.200000,2019-05-10 14:14:03,14,0,0,0,0,0,0,1
630,Thu,12,Jul,2012,14:13:22,PDT,1342127602,1266,12,11201536_1628709360682540_1956063825_n.jpg,...,2532.200000,2019-05-10 14:13:22,14,0,0,0,0,1,0,0
631,Wed,11,Jul,2012,17:35:03,PDT,1342053303,1180,10,11201753_1464295487195491_160635000_n.jpg,...,2523.100000,2019-05-10 17:35:03,17,0,0,0,0,0,0,1
632,Tue,10,Jul,2012,20:59:34,PDT,1341979174,2840,14,11190928_918529471532673_1993129764_n.jpg,...,2272.500000,2019-05-10 20:59:34,20,0,0,0,0,0,1,0
633,Tue,10,Jul,2012,15:49:40,PDT,1341960580,1382,20,11190704_718316164944694_2105568128_n.jpg,...,2193.800000,2019-05-10 15:49:40,15,0,0,0,0,0,1,0
634,Sat,07,Jul,2012,15:30:04,PDT,1341700204,7624,170,11203352_1581909165410241_635207692_n.jpg,...,1503.300000,2019-05-10 15:30:04,15,0,0,1,0,0,0,0
635,Sun,01,Jul,2012,21:29:20,PDT,1341203360,1347,25,11186893_1576569115953627_442196420_n.jpg,...,1541.900000,2019-05-10 21:29:20,21,0,0,0,1,0,0,0
636,Sun,01,Jul,2012,21:14:31,PDT,1341202471,791,11,10643834_858243924248275_921856899_n.jpg,...,1514.500000,2019-05-10 21:14:31,21,0,0,0,1,0,0,0
637,Thu,28,Jun,2012,01:42:04,PDT,1340872924,2519,63,11176151_986554258023317_231147204_n.jpg,...,1341.800000,2019-05-10 01:42:04,1,0,0,0,0,1,0,0
638,Sat,26,May,2012,15:02:24,PDT,1338069744,5760,159,11193136_1380077572323137_737961216_n.jpg,...,815.500000,2019-05-10 15:02:24,15,0,0,1,0,0,0,0
639,Sat,12,May,2012,10:11:01,PDT,1336842661,573,3,11191565_377948729074029_1541419444_n.jpg,...,795.800000,2019-05-10 10:11:01,10,0,0,1,0,0,0,0
640,Thu,03,May,2012,12:37:40,PDT,1336073860,1306,21,11123817_1583074211909596_1792898085_n.jpg,...,683.400000,2019-05-10 12:37:40,12,0,0,0,0,1,0,0
641,Sun,15,Apr,2012,15:30:56,PDT,1334529056,1089,3,11137758_851711641566868_584371548_n.jpg,...,593.900000,2019-05-10 15:30:56,15,0,0,0,1,0,0,0
642,Fri,13,Apr,2012,08:40:05,PDT,1334331605,334,5,11176162_467690613400025_1192413245_n.jpg,...,578.000000,2019-05-10 08:40:05,8,1,0,0,0,0,0,0
643,Sun,08,Apr,2012,00:01:47,PDT,1333868507,595,8,11187006_1605936039619337_988186190_n.jpg,...,557.000000,2019-05-10 00:01:47,0,0,0,0,1,0,0,0
644,Fri,06,Apr,2012,10:24:29,PDT,1333733069,719,15,11093141_385899804931983_283116655_n.jpg,...,498.400000,2019-05-10 10:24:29,10,1,0,0,0,0,0,0
645,Mon,26,Mar,2012,13:58:25,PDT,1332795505,1733,98,11189207_860854694008625_1805270530_n.jpg,...,359.000000,2019-05-10 13:58:25,13,0,1,0,0,0,0,0
646,Sun,04,Mar,2012,11:42:57,PST,1330890177,517,4,11186969_718117511630181_1647171176_n.jpg,...,341.444444,2019-05-10 11:42:57,11,0,0,0,1,0,0,0
647,Fri,02,Mar,2012,11:21:40,PST,1330716100,792,14,11084636_445273002295367_1060544385_n.jpg,...,285.125000,2019-05-10 11:21:40,11,1,0,0,0,0,0,0
648,Sat,25,Feb,2012,15:18:23,PST,1330211903,497,10,11098739_1421638834811409_1766098251_n.jpg,...,254.857143,2019-05-10 15:18:23,15,0,0,1,0,0,0,0
649,Thu,23,Feb,2012,15:30:57,PST,1330039857,376,4,11084982_384739128376570_2048904125_n.jpg,...,234.666667,2019-05-10 15:30:57,15,0,0,0,0,1,0,0
650,Wed,22,Feb,2012,14:22:06,PST,1329949326,182,5,11137865_1543718562515398_225441497_n.jpg,...,245.200000,2019-05-10 14:22:06,14,0,0,0,0,0,0,1
651,Fri,17,Feb,2012,14:32:01,PST,1329517921,194,2,11098266_843548769027098_2140053411_n.jpg,...,258.000000,2019-05-10 14:32:01,14,1,0,0,0,0,0,0
652,Thu,16,Feb,2012,12:17:43,PST,1329423463,175,7,11142379_823914911028154_816138370_n.jpg,...,285.666667,2019-05-10 12:17:43,12,0,0,0,0,1,0,0
653,Fri,20,Jan,2012,16:10:17,PST,1327104617,385,21,11123750_460993327385771_711397626_n.jpg,...,236.000000,2019-05-10 16:10:17,16,1,0,0,0,0,0,0
654,Tue,17,Jan,2012,13:05:08,PST,1326834308,133,1,11191007_620846191379914_1897693273_n.jpg,...,339.000000,2019-05-10 13:05:08,13,0,0,0,0,0,1,0
655,Sun,15,Jan,2012,16:10:27,PST,1326672627,339,5,11187064_1589153338021863_1371648683_n.jpg,...,0.000000,2019-05-10 16:10:27,16,0,0,0,1,0,0,0

In [24]:
X = new_AB_df.drop(['DOW', 'day', 'month', 'year', 'time', 'timezone', 'num_comments', 'name', 'num_likes', 'objects', 'datetime'], axis=1)
print(X.columns)

Index(['epoch', 'is_person', 'is_bicycle', 'is_car', 'is_motorcycle',
       'is_airplane', 'is_bus', 'is_train', 'is_truck', 'is_boat',
       ...
       'is_toothbrush', 'previous_likes', 'hour', 'Fri', 'Mon', 'Sat', 'Sun',
       'Thu', 'Tue', 'Wed'],
      dtype='object', length=102)

In [34]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
Y = new_AB_df.loc[:, 'num_likes']
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.24, shuffle = True, random_state=100)
LinearRegressionModel = linear_model.LinearRegression() 
LinearRegressionModel.fit(x_train, y_train)

print("Training: ", LinearRegressionModel.score(x_train, y_train))
print("Testing: ", LinearRegressionModel.score(x_test, y_test))

Training:  0.5537141985180483
Testing:  0.5103785034010311