In [2]:
import numpy as np 
import pandas as pd
import json
import time
from xgboost import XGBClassifier

In [3]:
image_DF = pd.read_csv('AOC_output.csv', names=['name', 'objects'])
image_DF

,name,objects
0,11176210_859954387410261_1985799031_n.jpg,"['person', 'person']"
1,23421155_325907524543476_3735144920583766016_n...,"['person', 'person', 'bottle']"
2,11378391_944585778918991_1917638315_n.jpg,['person']
3,47586205_2261195664123134_5969231701740536350_...,"['person', 'chair']"
4,11374002_1615738015368989_1991728466_n.jpg,"['dog', 'bed']"
5,13298032_492428684281391_1587643377_n.jpg,"['dog', 'couch']"
6,26868100_340709193081439_9106740417520467968_n...,"['tv', 'person', 'person', 'person', 'person',..."
7,11850367_1027305420622130_560170916_n.jpg,"['dog', 'person', 'person']"
8,41863396_1886803911416727_8213046552232438563_...,['person']
9,10362077_224306174445711_177294697_n.jpg,"['bird', 'person', 'bird', 'bird', 'bench', 'b..."
10,25025389_183599632385515_8686203436376522752_n...,['person']
11,53006843_2419515061610153_57865838088577126_n.jpg,['person']
12,39314906_449174282155812_4994793480573157376_n...,['person']
13,28752719_175468599742313_5048040359100153856_n...,"['dog', 'dog']"
14,11358938_1432593413715328_496433075_n.jpg,['person']
15,10995258_1381273755520716_1093787198_n.jpg,['dog']
16,10735508_732400903514944_610578641_n.jpg,"['couch', 'dog']"
17,929062_276535559193444_134110235_n.jpg,"['person', 'person', 'tv', 'person', 'person']"
18,11084786_1557231134559744_1080397709_n.jpg,"['person', 'person', 'person']"
19,22344464_155729481690108_8225024837567905792_n...,"['train', 'person']"
20,52268842_2229878900561556_3055825140039732399_...,[]
21,11378807_432260806953037_768035794_n.jpg,"['person', 'person', 'person', 'person']"
22,16464978_216450785485653_5207215467747344384_n...,['clock']
23,11372228_435912296588597_549461031_n.jpg,[]
24,12912380_1051617041550484_1261559287_n.jpg,"['person', 'person']"
25,17932187_1891693874419178_1357649684935475200_...,['person']
26,916481_694882087219712_1308997221_n.jpg,['dog']
27,11287528_1448967935402430_1523460010_n.jpg,"['person', 'person', 'person']"
28,10369317_1449785921927536_419911585_n.jpg,['person']
29,29416879_1482701571840610_7660927414913990656_...,['person']
...,...,...
1127,30899972_1757371410993013_2833507796253671424_...,['person']
1128,12784100_823612631095594_2039492494_n.jpg,"['person', 'person']"
1129,11376533_486051451561328_836771466_n.jpg,[]
1130,11356779_922559737785636_429688416_n.jpg,['person']
1131,1515934_266158930232214_1530163863_n.jpg,[]
1132,28435550_656785334712739_9131469134108819456_n...,['person']
1133,11355901_773883382731000_1437744476_n.jpg,['dog']
1134,12230940_1680076965547083_130137531_n.jpg,['person']
1135,22159448_285157035334984_8116524699426488320_n...,"['person', 'person', 'person', 'person', 'pers..."
1136,11280044_1591074037807984_1708705357_n.jpg,['person']
1137,20214238_1826663880996658_7687668108932153344_...,"['person', 'person', 'person']"
1138,13706829_502219489969406_55181658_n.jpg,"['person', 'person', 'person']"
1139,10483360_1433486860256600_315747093_n.jpg,"['person', 'person', 'person', 'person']"
1140,10844201_756190791126669_1453957236_n.jpg,"['potted plant', 'traffic light', 'person', 'p..."
1141,10488683_664849773595695_712619029_n.jpg,[]
1142,20398812_343853279380107_3415866462072471552_n...,['dog']
1143,11311204_1858003987758243_1090003552_n.jpg,"['person', 'person']"
1144,18013842_590148527859330_7359270103411589120_n...,"['person', 'person']"
1145,15803011_1334309163309739_2846935393029324800_...,"['person', 'person', 'person', 'person', 'pers..."
1146,15275711_1829762860646154_1874201961356591104_...,"['bed', 'dog']"
1147,14033516_1237251042975468_1605774789_n.jpg,[]
1148,12345972_1533529240303648_1864876696_n.jpg,"['dog', 'bed']"
1149,11246294_384968628375470_1897300670_n.jpg,[]
1150,11244432_839831509435870_1158623794_n.jpg,"['person', 'person', 'bench']"
1151,1538493_693777894028329_1348552558_n.jpg,"['person', 'person', 'person', 'person', 'pers..."
1152,13151363_1594302634214475_837482046_n.jpg,"['person', 'person', 'person', 'person', 'pers..."
1153,12750330_1694239550848899_1313561339_n.jpg,['person']
1154,16123057_367740046926790_1699880684899794944_n...,"['person', 'dog', 'tie']"
1155,11334633_846310468783174_1616363392_n.jpg,"['person', 'person', 'person', 'person', 'pers..."
1156,917124_1436331153289634_1529578324_n.jpg,"['person', 'wine glass', 'wine glass', 'dining..."

In [4]:
!ls

54511586_1301069350049619_3770365202227246635_n.jpg
58057878_424768844754613_3912836086531526992_n.jpg
AOC_output.csv
JuliaH_output.csv
New Folder With Items
Uber
Untitled.ipynb
Untitled1.ipynb
Untitled2.ipynb
YOLO-JuliaH.ipynb
YOLO-imjennim.ipynb
YOLO.ipynb
YOLO_AOC.ipynb
YOLO_Kylie.ipynb
YOLO_chung.ipynb
alexachung
alexachung.json
alexandradaddario.json
alia_image_output.csv
aliaabhatt_images
blondeblissblog
chung.csv
darknet
dsa2018materials
imjennim.json
imjennim_output.csv
instagram-scraper.log
juliaH_model.sav
juliahengel.json
keras
kylie_model.sav
kylie_output.csv
kyliejenner
kyliejenner.json
like_predictor_AOC.ipynb
like_predictor_JuliaH.ipynb
like_predictor_Kylie.ipynb
like_predictor_blondebliss.ipynb
like_predictor_chung.ipynb
like_predictor_imjennim.ipynb
memnet
memnet_trial.ipynb
out
output.txt
paceman.pem
sol0.pdf
sol1.pdf
sol10.pdf
sol11.pdf
sol12.pdf
sol13.pdf
sol14.pdf
sol2.pdf
sol3.pdf
sol4.pdf
sol5.pdf
sol6.pdf
sol7.pdf
sol8.pdf
sol9.pdf
team_30_data-x
team_30_data-x-master
team_30_data-x-master.zip
yolo
yolo.zip
yolov3.cfg
yolov3.txt
yolov3.weights

In [6]:
with open('./alexandradaddario.json') as json_file:  
    AB_data = json.load(json_file)

In [7]:
data = [['DOW', 'day', 'month', 'year', 'time', 'timezone', 'epoch', 'num_likes', 'num_comments', 'url']]

In [8]:
for entry in AB_data['GraphImages']: 
    if entry['is_video'] == False:
        epoch = entry['taken_at_timestamp']
        text_entry = entry['edge_media_to_caption']['edges']
        text = ''
        if (len(text_entry) > 0):
            text = text_entry[0]['node']['text']
        #num_hashtags = len([i.strip("#") for i in text.split() if text.startswith("#")])
        #num_mentions = len([i.strip("@") for i in text.split() if text.startswith("@")])
        t = time.strftime("%a, %d %b %Y %H:%M:%S %Z", time.localtime(epoch))
        row = t.split(' ')
        row[0] = row[0][:len(row[0])-1]
        row.append(epoch)
        row.append(entry['edge_media_preview_like']['count'])
        row.append(entry['edge_media_to_comment']['count'])
        temp_url = entry['display_url'].split('.jpg')[0].split('/')[8] + '.jpg'
        row.append(temp_url)
        #ow.append(num_mentions)
        #row.append(num_mentions)
        data.append(row)

In [9]:
AB_df = pd.DataFrame(data, columns=['DOW', 'day', 'month', 'year', 'time', 'timezone', 'epoch', 'num_likes', 'num_comments', 'url'])
AB_df = AB_df.drop([0])

In [10]:
AB_df.head()

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,url
1,Thu,09,May,2019,13:04:36,PDT,1557432276,1420850,8349,p1080x1080.jpg
2,Thu,09,May,2019,00:49:42,PDT,1557388182,151889,382,p1080x1080.jpg
3,Mon,22,Apr,2019,14:04:46,PDT,1555967086,908250,2541,58895262_2132607996857934_4701254045807261576_...
4,Sat,13,Apr,2019,09:21:10,PDT,1555172470,983130,2296,55866960_2389786801045353_5292221046455748089_...
5,Tue,09,Apr,2019,12:31:15,PDT,1554838275,220840,621,54513910_159355088402720_621118627925394567_n.jpg

In [11]:
new_AB_df = AB_df.merge(image_DF, how='inner', left_on='url', right_on='name')
new_AB_df = new_AB_df.drop(columns=['url'])
text_file = open("./yolo/yolov3.txt", "r")
lines = text_file.read().split()

In [12]:
for item in lines:
    temp_item = []
    for i in new_AB_df['objects']:
        count = i.count(item)
        if count > 0:
            temp_item.append(1)
        else:
            temp_item.append(0)
    category = 'is_' + item
    new_AB_df[category] = temp_item
    
new_AB_df.head()

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,name,...,is_sink,is_refrigerator,is_book,is_clock,is_vase,is_scissors,is_teddy,is_hair,is_drier,is_toothbrush
0,Mon,22,Apr,2019,14:04:46,PDT,1555967086,908250,2541,58895262_2132607996857934_4701254045807261576_...,...,0,0,0,0,0,0,0,0,0,0
1,Sat,13,Apr,2019,09:21:10,PDT,1555172470,983130,2296,55866960_2389786801045353_5292221046455748089_...,...,0,0,0,0,0,0,0,0,0,0
2,Tue,09,Apr,2019,12:31:15,PDT,1554838275,220840,621,54513910_159355088402720_621118627925394567_n.jpg,...,0,0,0,0,0,0,0,0,0,0
3,Mon,08,Apr,2019,20:23:28,PDT,1554780208,298768,453,56218114_312795856031875_8218982249137127703_n...,...,0,0,0,0,0,0,0,0,0,0
4,Sat,06,Apr,2019,18:19:06,PDT,1554599946,1490341,8202,55816649_550966662092678_550708198541798994_n.jpg,...,0,0,0,0,0,0,0,0,0,0

In [13]:
curr_index = 1
previous_likes = np.array([])
while (curr_index <= len(new_AB_df)):
    end_index = min(len(new_AB_df) + 1, curr_index + 10)
    previous_likes = np.append(previous_likes, new_AB_df['num_likes'][curr_index:end_index].mean())
    curr_index=curr_index + 1
    
previous_likes[len(new_AB_df) - 1] = 0
new_AB_df['previous_likes'] = previous_likes

In [14]:
new_AB_df.head()

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,name,...,is_refrigerator,is_book,is_clock,is_vase,is_scissors,is_teddy,is_hair,is_drier,is_toothbrush,previous_likes
0,Mon,22,Apr,2019,14:04:46,PDT,1555967086,908250,2541,58895262_2132607996857934_4701254045807261576_...,...,0,0,0,0,0,0,0,0,0,781432.0
1,Sat,13,Apr,2019,09:21:10,PDT,1555172470,983130,2296,55866960_2389786801045353_5292221046455748089_...,...,0,0,0,0,0,0,0,0,0,701213.1
2,Tue,09,Apr,2019,12:31:15,PDT,1554838275,220840,621,54513910_159355088402720_621118627925394567_n.jpg,...,0,0,0,0,0,0,0,0,0,729088.4
3,Mon,08,Apr,2019,20:23:28,PDT,1554780208,298768,453,56218114_312795856031875_8218982249137127703_n...,...,0,0,0,0,0,0,0,0,0,722441.3
4,Sat,06,Apr,2019,18:19:06,PDT,1554599946,1490341,8202,55816649_550966662092678_550708198541798994_n.jpg,...,0,0,0,0,0,0,0,0,0,623270.3

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
avg_likes = new_AB_df['num_likes'].mean()

In [17]:
new_AB_df['datetime'] = pd.to_datetime(new_AB_df['time'])
new_AB_df['hour'] = [i.hour for i in new_AB_df['datetime']]

In [18]:
new_AB_df.shape[0]

1081

In [19]:
days = pd.get_dummies(new_AB_df['DOW'])

In [20]:
months = pd.get_dummies(new_AB_df['month'])

In [21]:
new_AB_df = new_AB_df.merge(days, left_index = True, right_index = True)

In [22]:
new_AB_df = new_AB_df.dropna()
new_AB_df.loc[:, (new_AB_df != 0).any(axis=0)]

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,name,...,previous_likes,datetime,hour,Fri,Mon,Sat,Sun,Thu,Tue,Wed
0,Mon,22,Apr,2019,14:04:46,PDT,1555967086,908250,2541,58895262_2132607996857934_4701254045807261576_...,...,781432.000000,2019-05-10 14:04:46,14,0,1,0,0,0,0,0
1,Sat,13,Apr,2019,09:21:10,PDT,1555172470,983130,2296,55866960_2389786801045353_5292221046455748089_...,...,701213.100000,2019-05-10 09:21:10,9,0,0,1,0,0,0,0
2,Tue,09,Apr,2019,12:31:15,PDT,1554838275,220840,621,54513910_159355088402720_621118627925394567_n.jpg,...,729088.400000,2019-05-10 12:31:15,12,0,0,0,0,0,1,0
3,Mon,08,Apr,2019,20:23:28,PDT,1554780208,298768,453,56218114_312795856031875_8218982249137127703_n...,...,722441.300000,2019-05-10 20:23:28,20,0,1,0,0,0,0,0
4,Sat,06,Apr,2019,18:19:06,PDT,1554599946,1490341,8202,55816649_550966662092678_550708198541798994_n.jpg,...,623270.300000,2019-05-10 18:19:06,18,0,0,1,0,0,0,0
5,Mon,01,Apr,2019,17:32:09,PDT,1554165129,201040,860,56197364_2298105753808739_2517613076033450095_...,...,662952.400000,2019-05-10 17:32:09,17,0,1,0,0,0,0,0
6,Fri,29,Mar,2019,12:01:14,PDT,1553886074,1553631,8093,53309133_2391815541048978_3708328543625124450_...,...,547348.300000,2019-05-10 12:01:14,12,1,0,0,0,0,0,0
7,Mon,25,Mar,2019,18:24:20,PDT,1553563460,228338,666,54512990_280746859523127_5406331590509594418_n...,...,533052.800000,2019-05-10 18:24:20,18,0,1,0,0,0,0,0
8,Sat,16,Mar,2019,12:29:36,PDT,1552764576,942528,5094,52341753_433324384103357_6412086362471328676_n...,...,498487.200000,2019-05-10 12:29:36,12,0,0,1,0,0,0,0
9,Fri,15,Mar,2019,17:18:01,PDT,1552695481,1355601,4780,52717606_123109688786442_6805636688350410914_n...,...,392725.500000,2019-05-10 17:18:01,17,1,0,0,0,0,0,0
10,Tue,12,Mar,2019,17:38:22,PDT,1552437502,540103,1473,54463758_848806248796547_943709887604619203_n.jpg,...,530514.400000,2019-05-10 17:38:22,17,0,0,0,0,0,1,0
11,Thu,07,Mar,2019,14:17:18,PST,1551997038,180941,733,52878265_124883921907334_5829701641417762106_n...,...,531867.400000,2019-05-10 14:17:18,14,0,0,0,0,1,0,0
12,Wed,06,Mar,2019,14:25:22,PST,1551911122,499593,1402,53006843_2419515061610153_57865838088577126_n.jpg,...,513667.300000,2019-05-10 14:25:22,14,0,0,0,0,0,0,1
13,Tue,26,Feb,2019,08:59:54,PST,1551200394,232297,844,51644535_2269001696498110_8523864606366572930_...,...,547458.500000,2019-05-10 08:59:54,8,0,0,0,0,0,1,0
14,Fri,22,Feb,2019,04:02:31,PST,1550836951,498631,1140,51856876_408660233220265_302453641642345661_n.jpg,...,512222.800000,2019-05-10 04:02:31,4,1,0,0,0,0,0,0
15,Wed,20,Feb,2019,13:06:54,PST,1550696814,597861,1467,51934387_304377100223933_3460514612766190206_n...,...,478415.100000,2019-05-10 13:06:54,13,0,0,0,0,0,0,1
16,Tue,19,Feb,2019,15:01:00,PST,1550617260,397590,1176,51359120_2204399519604045_1183326149913180051_...,...,461922.700000,2019-05-10 15:01:00,15,0,0,0,0,0,1,0
17,Tue,19,Feb,2019,12:39:50,PST,1550608790,85383,280,51033726_2135779929839632_7502958807451828386_...,...,499920.900000,2019-05-10 12:39:50,12,0,0,0,0,0,1,0
18,Sun,17,Feb,2019,15:59:57,PST,1550447997,596872,2372,52283990_315296335997083_2057693618594689686_n...,...,489597.000000,2019-05-10 15:59:57,15,0,0,0,1,0,0,0
19,Thu,14,Feb,2019,20:02:46,PST,1550203366,297984,943,50705085_281815839153871_2361688458824855094_n...,...,499193.800000,2019-05-10 20:02:46,20,0,0,0,0,1,0,0
20,Sun,10,Feb,2019,18:44:26,PST,1549853066,1917992,20605,51364680_242197753353635_1407878962625180515_n...,...,344600.500000,2019-05-10 18:44:26,18,0,0,0,1,0,0,0
21,Fri,08,Feb,2019,17:08:54,PST,1549674534,194471,481,50609378_1469663919832517_8681874072643338255_...,...,468602.000000,2019-05-10 17:08:54,17,1,0,0,0,0,0,0
22,Sun,03,Feb,2019,12:01:41,PST,1549224101,317592,1070,49933690_342654423003264_2694310366876476617_n...,...,478220.100000,2019-05-10 12:01:41,12,0,0,0,1,0,0,0
23,Thu,31,Jan,2019,13:51:34,PST,1548971494,570209,1634,50295439_316412125747532_6815331087520488865_n...,...,451656.700000,2019-05-10 13:51:34,13,0,0,0,0,1,0,0
24,Wed,30,Jan,2019,12:24:59,PST,1548879899,146274,548,49913275_982412138619307_4556591518574546489_n...,...,449644.800000,2019-05-10 12:24:59,12,0,0,0,0,0,0,1
25,Fri,25,Jan,2019,11:26:12,PST,1548444372,259784,513,49844031_2778231025550281_4678973455825230016_...,...,501383.600000,2019-05-10 11:26:12,11,1,0,0,0,0,0,0
26,Fri,25,Jan,2019,10:21:53,PST,1548440513,232666,559,50626717_983898311808737_6601892756295630895_n...,...,608537.000000,2019-05-10 10:21:53,10,1,0,0,0,0,0,0
27,Thu,24,Jan,2019,19:46:36,PST,1548387996,465365,1447,50088356_124506828597697_5934665806814798326_n...,...,578156.500000,2019-05-10 19:46:36,19,0,0,0,0,1,0,0
28,Tue,22,Jan,2019,14:00:55,PST,1548194455,493633,1218,50058441_1466397820158671_4253554198902939345_...,...,582243.700000,2019-05-10 14:00:55,14,0,0,0,0,0,1,0
29,Tue,22,Jan,2019,10:51:59,PST,1548183119,393952,1142,49434137_278993989435449_862821760412409118_n.jpg,...,669352.000000,2019-05-10 10:51:59,10,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,Wed,03,Jul,2013,22:33:48,PDT,1372916028,4132,49,11280044_1591074037807984_1708705357_n.jpg,...,7772.700000,2019-05-10 22:33:48,22,0,0,0,0,0,0,1
1052,Mon,24,Jun,2013,15:59:23,PDT,1372114763,3759,62,11326995_682894091817174_1013993224_n.jpg,...,7692.700000,2019-05-10 15:59:23,15,0,1,0,0,0,0,0
1053,Sat,22,Jun,2013,22:46:30,PDT,1371966390,3139,34,11325413_1623440201202075_686615643_n.jpg,...,7702.800000,2019-05-10 22:46:30,22,0,0,1,0,0,0,0
1054,Sat,22,Jun,2013,22:35:41,PDT,1371965741,3221,27,11350960_441535856027194_2008895398_n.jpg,...,7703.800000,2019-05-10 22:35:41,22,0,0,1,0,0,0,0
1055,Thu,20,Jun,2013,16:54:00,PDT,1371772440,3784,76,11379015_1449936988653849_1023060108_n.jpg,...,7718.700000,2019-05-10 16:54:00,16,0,0,0,0,1,0,0
1056,Thu,20,Jun,2013,15:57:42,PDT,1371769062,28614,1060,11375384_1605851589696946_596506148_n.jpg,...,5507.600000,2019-05-10 15:57:42,15,0,0,0,0,1,0,0
1057,Thu,20,Jun,2013,15:56:54,PDT,1371769014,22562,684,11358938_1432593413715328_496433075_n.jpg,...,3602.200000,2019-05-10 15:56:54,15,0,0,0,0,1,0,0
1058,Fri,14,Jun,2013,18:00:46,PDT,1371258046,3257,32,11259911_374562052742397_1248121563_n.jpg,...,3642.200000,2019-05-10 18:00:46,18,1,0,0,0,0,0,0
1059,Fri,14,Jun,2013,17:54:42,PDT,1371257682,3461,28,11335535_823090821099968_1038624478_n.jpg,...,3640.800000,2019-05-10 17:54:42,17,1,0,0,0,0,0,0
1060,Thu,13,Jun,2013,11:04:05,PDT,1371146645,3017,23,11335622_1593068667597974_151768550_n.jpg,...,4394.000000,2019-05-10 11:04:05,11,0,0,0,0,1,0,0
1061,Thu,13,Jun,2013,10:59:49,PDT,1371146389,2913,16,11373616_807075279362206_1714011547_n.jpg,...,4656.800000,2019-05-10 10:59:49,10,0,0,0,0,1,0,0
1062,Wed,12,Jun,2013,13:03:25,PDT,1371067405,2959,33,11363783_793090900797778_204427964_n.jpg,...,4906.000000,2019-05-10 13:03:25,13,0,0,0,0,0,0,1
1063,Wed,12,Jun,2013,13:02:24,PDT,1371067344,3240,33,11335480_1584831211785815_1108562207_n.jpg,...,5239.400000,2019-05-10 13:02:24,13,0,0,0,0,0,0,1
1064,Fri,07,Jun,2013,19:39:25,PDT,1370659165,3231,19,11348271_474024359430696_1398343600_n.jpg,...,5501.300000,2019-05-10 19:39:25,19,1,0,0,0,0,0,0
1065,Thu,06,Jun,2013,16:02:34,PDT,1370559754,3933,50,11374002_1615738015368989_1991728466_n.jpg,...,5630.400000,2019-05-10 16:02:34,16,0,0,0,0,1,0,0
1066,Sun,02,Jun,2013,19:45:04,PDT,1370227504,6503,773,11356510_1645388462363417_1245161565_n.jpg,...,5866.400000,2019-05-10 19:45:04,19,0,0,0,1,0,0,0
1067,Fri,24,May,2013,17:58:42,PDT,1369443522,3508,32,11355901_773883382731000_1437744476_n.jpg,...,6060.800000,2019-05-10 17:58:42,17,1,0,0,0,0,0,0
1068,Wed,22,May,2013,15:11:06,PDT,1369260666,3657,41,11357669_379456305596597_2059875668_n.jpg,...,6397.500000,2019-05-10 15:11:06,15,0,0,0,0,0,0,1
1069,Tue,15,Jan,2013,15:31:24,PST,1358292684,3447,37,11269535_885172498220179_341650311_n.jpg,...,6969.700000,2019-05-10 15:31:24,15,0,0,0,0,0,1,0
1070,Sat,04,Aug,2012,10:23:06,PDT,1344100986,10549,144,11205762_837858302930538_2083269032_n.jpg,...,7686.300000,2019-05-10 10:23:06,10,0,0,1,0,0,0,0
1071,Sat,04,Aug,2012,10:22:37,PDT,1344100957,5541,40,10914308_1441824302500886_1975572502_n.jpg,...,7924.666667,2019-05-10 10:22:37,10,0,0,1,0,0,0,0
1072,Sat,04,Aug,2012,10:20:59,PDT,1344100859,5451,34,11203386_1120155038010896_1854595928_n.jpg,...,8233.875000,2019-05-10 10:20:59,10,0,0,1,0,0,0,0
1073,Sat,04,Aug,2012,10:19:56,PDT,1344100796,6574,55,11189198_100174176984972_1166736504_n.jpg,...,8471.000000,2019-05-10 10:19:56,10,0,0,1,0,0,0,0
1074,Sat,04,Aug,2012,07:17:15,PDT,1344089835,5850,55,11203423_1566798343583542_1683851024_n.jpg,...,8907.833333,2019-05-10 07:17:15,7,0,0,1,0,0,0,0
1075,Fri,03,Aug,2012,17:33:32,PDT,1344040412,5224,50,11230341_457404767758708_1038869733_n.jpg,...,9644.600000,2019-05-10 17:33:32,17,1,0,0,0,0,0,0
1076,Fri,03,Aug,2012,17:24:45,PDT,1344039885,8863,167,11195763_485556291596386_611998296_n.jpg,...,9840.000000,2019-05-10 17:24:45,17,1,0,0,0,0,0,0
1077,Fri,03,Aug,2012,17:20:26,PDT,1344039626,5452,57,11186819_1588038521485023_1571947590_n.jpg,...,11302.666667,2019-05-10 17:20:26,17,1,0,0,0,0,0,0
1078,Fri,03,Aug,2012,17:20:00,PDT,1344039600,7024,85,11193181_1568357610092374_1579087869_n.jpg,...,13442.000000,2019-05-10 17:20:00,17,1,0,0,0,0,0,0
1079,Fri,03,Aug,2012,17:11:25,PDT,1344039085,9169,132,11189647_1583873451890682_1696710695_n.jpg,...,17715.000000,2019-05-10 17:11:25,17,1,0,0,0,0,0,0
1080,Fri,03,Aug,2012,16:58:59,PDT,1344038339,17715,868,11203406_771275072991447_1465117043_n.jpg,...,0.000000,2019-05-10 16:58:59,16,1,0,0,0,0,0,0

In [23]:
X = new_AB_df.drop(['DOW', 'day', 'month', 'year', 'time', 'timezone', 'num_comments', 'name', 'num_likes', 'objects', 'datetime'], axis=1)
print(X.columns)

Index(['epoch', 'is_person', 'is_bicycle', 'is_car', 'is_motorcycle',
       'is_airplane', 'is_bus', 'is_train', 'is_truck', 'is_boat',
       ...
       'is_toothbrush', 'previous_likes', 'hour', 'Fri', 'Mon', 'Sat', 'Sun',
       'Thu', 'Tue', 'Wed'],
      dtype='object', length=102)

In [29]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.externals import joblib
Y = new_AB_df.loc[:, 'num_likes']
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, shuffle = True, random_state=100)
LinearRegressionModel = linear_model.LinearRegression() 
LinearRegressionModel.fit(x_train, y_train)
print("Training: ", LinearRegressionModel.score(x_train, y_train))
print("Testing: ", LinearRegressionModel.score(x_test, y_test))

filename = 'alexandria_model.sav'
joblib.dump(LinearRegressionModel, filename)

Training:  0.602950612499154
Testing:  0.5384327969040794

['alexandria_model.sav']