In [1]:
import numpy as np 
import pandas as pd
import json
import time
from xgboost import XGBClassifier

In [3]:
image_DF = pd.read_csv('chung.csv', names=['name', 'objects'])
image_DF

,name,objects
0,12750352_556303677861859_1861200847_n.jpg,['person']
1,1388992_617195158337389_659074600_n.jpg,['person']
2,10808477_1524845041107195_1574814843_n.jpg,[]
3,11195644_859987957388926_2050093219_n.jpg,[]
4,11193180_850679434968977_1340350303_n.jpg,['person']
5,10755744_477200675751036_1863143282_n.jpg,"['person', 'couch']"
6,11325838_365603313564408_945118434_n.jpg,"['person', 'person']"
7,11189791_815703235192850_1329519263_n.jpg,"['person', 'tie']"
8,13731138_1769246626686129_955733884_n.jpg,['person']
9,14276465_338541259819103_106006855_n.jpg,"['person', 'person', 'person']"
10,11410209_795019830594397_1808287602_n.jpg,"['bench', 'person', 'tie']"
11,11098475_1414740895499976_146896118_n.jpg,"['person', 'person', 'person', 'person']"
12,11184528_1582216948697725_1409123620_n.jpg,[]
13,926862_1521630288068800_1278769622_n.jpg,['person']
14,46378404_739493896417846_1788925918630548748_n...,"['umbrella', 'umbrella', 'chair', 'chair', 'ch..."
15,1389059_543467752413404_108915500_n.jpg,"['person', 'person', 'cup', 'dining table', 'w..."
16,11248917_848755848537665_436897119_n.jpg,"['person', 'person']"
17,22280482_1483232011772574_3722192720853204992_...,['person']
18,14547557_2182714091953610_2385426854833029120_...,['person']
19,11205914_100687650266962_915321807_n.jpg,"['person', 'person']"
20,19624730_466227957063325_477880128894926848_n.jpg,"['person', 'person', 'bench', 'cup']"
21,12142669_1501928323433336_1639166331_n.jpg,['person']
22,1390285_736815513056984_1364555771_n.jpg,"['person', 'cake', 'dining table']"
23,11208374_942670069087688_1997493196_n.jpg,['person']
24,11246801_1667576480142353_601173643_n.jpg,['person']
25,19534263_1519565064731671_4894174134973497344_...,"['person', 'person', 'wine glass', 'wine glass..."
26,13422917_1201918753172785_2066769649_n.jpg,['person']
27,12081224_439995802855982_725023786_n.jpg,['person']
28,15624016_1864739280429822_2734879670506881024_...,"['person', 'person', 'person', 'tie']"
29,10175262_639387206115927_678951290_n.jpg,['dog']
...,...,...
4472,10666103_369596059910131_2060870841_n.jpg,['person']
4473,46963618_215597132654787_808763298400305388_n.jpg,['person']
4474,11377639_1601760823418453_1593324382_n.jpg,"['person', 'person', 'person', 'person', 'pers..."
4475,12081298_178711112467067_679678874_n.jpg,['person']
4476,42496442_170150100583173_6007755447561285388_n...,['person']
4477,11374083_901618433210937_9675227_n.jpg,"['couch', 'person']"
4478,35324530_1950979628286100_3910499475977666560_...,['person']
4479,11256368_457546051067987_296643281_n.jpg,"['baseball bat', 'person', 'person', 'person',..."
4480,11311563_953738507982008_1137966346_n.jpg,[]
4481,15538356_692244747601450_7297026647083974656_n...,"['person', 'backpack', 'car']"
4482,41724492_707940109581209_4540522428935816343_n...,"['person', 'person', 'person']"
4483,11282164_1418669818455140_533023666_n.jpg,"['person', 'person', 'person', 'cup']"
4484,11195676_1417246128594152_134530634_n.jpg,"['person', 'person', 'person', 'cup']"
4485,1737036_1443388012557870_1163294514_n.jpg,"['person', 'person', 'person', 'person', 'pers..."
4486,11244806_1588061078130428_1505285092_n.jpg,"['person', 'bed', 'bed', 'chair', 'vase', 'bot..."
4487,10665359_805396659512844_2066060467_n.jpg,"['person', 'person', 'person']"
4488,11245883_888410874558810_8470144_n.jpg,['person']
4489,1742724_211697015695388_309429388_n.jpg,"['book', 'person', 'person']"
4490,10990593_840773555987940_1900660457_n.jpg,"['person', 'person', 'person']"
4491,11376361_408414416018865_2082016282_n.jpg,"['person', 'person', 'person', 'person', 'pers..."
4492,39907493_327589437797924_4578814124039300470_n...,['person']
4493,11176499_863530597033456_399552263_n.jpg,['person']
4494,11348410_893269134052403_113723540_n.jpg,['person']
4495,45802668_269962813712056_130939142385214684_n.jpg,['person']
4496,16465700_599986360203874_4167582766478655488_n...,['person']
4497,12317805_1661263074120002_1536125395_n.jpg,['person']
4498,11195686_1633184523569690_472745072_n.jpg,[]
4499,11380757_783319111765975_1062442219_n.jpg,"['person', 'person', 'cup', 'cup']"
4500,10932107_1527935987457147_1409618881_n.jpg,"['person', 'tv']"
4501,1169103_759472780735878_2075377492_n.jpg,"['car', 'person', 'handbag', 'person', 'tie']"

In [4]:
with open('alexachung.json') as json_file:  
    AB_data = json.load(json_file)

In [5]:
data = [['DOW', 'day', 'month', 'year', 'time', 'timezone', 'epoch', 'num_likes', 'num_comments', 'url']]

In [6]:
for entry in AB_data['GraphImages']: 
    if entry['is_video'] == False:
        epoch = entry['taken_at_timestamp']
        t = time.strftime("%a, %d %b %Y %H:%M:%S %Z", time.localtime(epoch))
        row = t.split(' ')
        row[0] = row[0][:len(row[0])-1]
        row.append(epoch)
        row.append(entry['edge_media_preview_like']['count'])
        row.append(entry['edge_media_to_comment']['count'])
        temp_url = entry['display_url'].split('.jpg')[0].split('/')[8] + '.jpg'
        row.append(temp_url)
        data.append(row)

In [7]:
AB_df = pd.DataFrame(data, columns=['DOW', 'day', 'month', 'year', 'time', 'timezone', 'epoch', 'num_likes', 'num_comments', 'url'])
AB_df = AB_df.drop([0])

In [8]:
AB_df.head()

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,url
1,Sun,05,May,2019,20:37:49,PDT,1557113869,8185,53,57939604_1405275606280969_2279277994967177982_...
2,Sun,05,May,2019,20:31:07,PDT,1557113467,3630,39,57568586_144722209994647_2830766459764292268_n...
3,Sun,05,May,2019,10:05:15,PDT,1557075915,13609,31,57487966_302650897331937_5403985171049488247_n...
4,Sat,04,May,2019,14:27:19,PDT,1557005239,10489,65,59343133_488375525034199_2400816836092659358_n...
5,Sat,04,May,2019,11:27:22,PDT,1556994442,33843,173,59652849_1688456544590726_3335026159453238735_...

In [9]:
new_AB_df = AB_df.merge(image_DF, how='inner', left_on='url', right_on='name')
new_AB_df = new_AB_df.drop(columns=['url'])
text_file = open("yolov3.txt", "r")
lines = text_file.read().split()

In [10]:
for item in lines:
    temp_item = []
    for i in new_AB_df['objects']:
        count = i.count(item)
        if count > 0:
            temp_item.append(1)
        else:
            temp_item.append(0)
    category = 'is_' + item
    new_AB_df[category] = temp_item
    
new_AB_df.head()

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,name,...,is_sink,is_refrigerator,is_book,is_clock,is_vase,is_scissors,is_teddy,is_hair,is_drier,is_toothbrush
0,Sun,05,May,2019,20:37:49,PDT,1557113869,8185,53,57939604_1405275606280969_2279277994967177982_...,...,0,0,0,0,0,0,0,0,0,0
1,Sun,05,May,2019,20:31:07,PDT,1557113467,3630,39,57568586_144722209994647_2830766459764292268_n...,...,0,0,0,0,0,0,0,0,0,0
2,Sun,05,May,2019,10:05:15,PDT,1557075915,13609,31,57487966_302650897331937_5403985171049488247_n...,...,0,0,0,0,0,0,0,0,0,0
3,Sat,04,May,2019,14:27:19,PDT,1557005239,10489,65,59343133_488375525034199_2400816836092659358_n...,...,0,0,0,0,0,0,0,1,0,0
4,Sat,04,May,2019,11:27:22,PDT,1556994442,33843,173,59652849_1688456544590726_3335026159453238735_...,...,0,0,0,0,0,0,0,0,0,0

In [11]:
curr_index = 1
previous_likes = np.array([])
while (curr_index <= len(new_AB_df)):
    end_index = min(len(new_AB_df) + 1, curr_index + 10)
    previous_likes = np.append(previous_likes, new_AB_df['num_likes'][curr_index:end_index].mean())
    curr_index=curr_index + 1
    
previous_likes[len(new_AB_df) - 1] = 0
new_AB_df['previous_likes'] = previous_likes

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
avg_likes = new_AB_df['num_likes'].mean()

In [14]:
new_AB_df['datetime'] = pd.to_datetime(new_AB_df['time'])
new_AB_df['hour'] = [i.hour for i in new_AB_df['datetime']]

In [15]:
days = pd.get_dummies(new_AB_df['DOW'])

In [16]:
months = pd.get_dummies(new_AB_df['month'])

In [17]:
new_AB_df = new_AB_df.merge(days, left_index = True, right_index = True)

In [18]:
new_AB_df = new_AB_df.dropna()
new_AB_df.loc[:, (new_AB_df != 0).any(axis=0)]

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,name,...,previous_likes,datetime,hour,Fri,Mon,Sat,Sun,Thu,Tue,Wed
0,Sun,05,May,2019,20:37:49,PDT,1557113869,8185,53,57939604_1405275606280969_2279277994967177982_...,...,22878.500000,2019-05-06 20:37:49,20,0,0,0,1,0,0,0
1,Sun,05,May,2019,20:31:07,PDT,1557113467,3630,39,57568586_144722209994647_2830766459764292268_n...,...,23529.600000,2019-05-06 20:31:07,20,0,0,0,1,0,0,0
2,Sun,05,May,2019,10:05:15,PDT,1557075915,13609,31,57487966_302650897331937_5403985171049488247_n...,...,27225.100000,2019-05-06 10:05:15,10,0,0,0,1,0,0,0
3,Sat,04,May,2019,14:27:19,PDT,1557005239,10489,65,59343133_488375525034199_2400816836092659358_n...,...,27713.000000,2019-05-06 14:27:19,14,0,0,1,0,0,0,0
4,Sat,04,May,2019,11:27:22,PDT,1556994442,33843,173,59652849_1688456544590726_3335026159453238735_...,...,29505.400000,2019-05-06 11:27:22,11,0,0,1,0,0,0,0
5,Fri,03,May,2019,18:09:27,PDT,1556932167,46387,136,57506371_2048427231922690_100519042340105452_n...,...,25817.300000,2019-05-06 18:09:27,18,1,0,0,0,0,0,0
6,Sun,28,Apr,2019,22:06:55,PDT,1556514415,19828,108,57390249_133704927745916_2471216704221332563_n...,...,24819.600000,2019-05-06 22:06:55,22,0,0,0,1,0,0,0
7,Sun,28,Apr,2019,15:32:45,PDT,1556490765,42790,141,57297988_2304886826394701_6394624463244656643_...,...,23192.200000,2019-05-06 15:32:45,15,0,0,0,1,0,0,0
8,Sun,28,Apr,2019,10:37:51,PDT,1556473071,10149,35,57360414_1797601237006227_794828059326291901_n...,...,22965.100000,2019-05-06 10:37:51,10,0,0,0,1,0,0,0
9,Fri,26,Apr,2019,18:00:23,PDT,1556326823,36261,162,58409500_414826195734552_6913565656830392035_n...,...,19907.100000,2019-05-06 18:00:23,18,1,0,0,0,0,0,0
10,Thu,25,Apr,2019,23:22:37,PDT,1556259757,11799,85,57088332_122917692224522_5474479344078602215_n...,...,21610.900000,2019-05-06 23:22:37,23,0,0,0,0,1,0,0
11,Tue,23,Apr,2019,09:19:19,PDT,1556036359,10141,56,58468504_134523251005302_8456419397446425258_n...,...,22857.200000,2019-05-06 09:19:19,9,0,0,0,0,0,1,0
12,Fri,19,Apr,2019,17:27:09,PDT,1555720029,50564,149,57377599_413289359449877_7886784572244922069_n...,...,21027.900000,2019-05-06 17:27:09,17,1,0,0,0,0,0,0
13,Thu,18,Apr,2019,13:20:26,PDT,1555618826,15368,76,56266974_439843096752481_5352641219803031247_n...,...,24039.800000,2019-05-06 13:20:26,13,0,0,0,0,1,0,0
14,Wed,17,Apr,2019,12:45:02,PDT,1555530302,51767,237,57597779_157638785257641_8323239045020188381_n...,...,19949.200000,2019-05-06 12:45:02,12,0,0,0,0,0,0,1
15,Mon,15,Apr,2019,04:26:05,PDT,1555327565,9506,148,56300320_428824071212684_2262205417619941290_n...,...,22479.800000,2019-05-06 04:26:05,4,0,1,0,0,0,0,0
16,Sat,13,Apr,2019,21:53:26,PDT,1555217606,9851,50,52964914_379070526014714_6818532364198952804_n...,...,23865.600000,2019-05-06 21:53:26,21,0,0,1,0,0,0,0
17,Thu,11,Apr,2019,16:37:41,PDT,1555025861,26516,122,56990432_319660148697202_2715111052209071843_n...,...,24571.100000,2019-05-06 16:37:41,16,0,0,0,0,1,0,0
18,Thu,11,Apr,2019,12:15:07,PDT,1555010107,7878,35,54732466_291817001734270_6529056325966210562_n...,...,24415.600000,2019-05-06 12:15:07,12,0,0,0,0,1,0,0
19,Wed,10,Apr,2019,18:27:15,PDT,1554946035,5681,28,55833144_425235891377953_3951855655351684049_n...,...,29065.900000,2019-05-06 18:27:15,18,0,0,0,0,0,0,1
20,Wed,10,Apr,2019,13:25:21,PDT,1554927921,28837,150,56653081_405336303627258_539003828065384699_n.jpg,...,27056.300000,2019-05-06 13:25:21,13,0,0,0,0,0,0,1
21,Tue,09,Apr,2019,04:57:35,PDT,1554811055,22604,81,56331134_2333949466878594_4819453031125472390_...,...,25802.200000,2019-05-06 04:57:35,4,0,0,0,0,0,1,0
22,Mon,08,Apr,2019,11:35:17,PDT,1554748517,32271,120,56213894_806777096362682_2512283851067967814_n...,...,24470.700000,2019-05-06 11:35:17,11,0,1,0,0,0,0,0
23,Sun,07,Apr,2019,17:29:44,PDT,1554683384,45487,158,56751364_1664599160310511_8933801597770132095_...,...,20960.300000,2019-05-06 17:29:44,17,0,0,0,1,0,0,0
24,Sat,06,Apr,2019,01:48:10,PDT,1554540490,10861,79,56257406_287838758826281_6124248407417621191_n...,...,21595.400000,2019-05-06 01:48:10,1,0,0,1,0,0,0,0
25,Thu,04,Apr,2019,15:49:01,PDT,1554418141,34812,217,56468364_337698250213039_4092020008329095101_n...,...,20246.600000,2019-05-06 15:49:01,15,0,0,0,0,1,0,0
26,Thu,04,Apr,2019,11:00:23,PDT,1554400823,23709,91,56252882_381075195811683_2615956411590206311_n...,...,19656.400000,2019-05-06 11:00:23,11,0,0,0,0,1,0,0
27,Wed,03,Apr,2019,00:54:51,PDT,1554278091,33571,180,54266492_2272020139708671_86956598098811410_n.jpg,...,16946.100000,2019-05-06 00:54:51,0,0,0,0,0,0,0,1
28,Mon,25,Mar,2019,11:46:29,PDT,1553539589,6323,40,54247464_2454666894577435_8140846316232352088_...,...,18953.200000,2019-05-06 11:46:29,11,0,1,0,0,0,0,0
29,Sun,24,Mar,2019,00:16:24,PDT,1553411784,52184,202,53815162_371228636940405_316165355631942558_n.jpg,...,19194.300000,2019-05-06 00:16:24,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4342,Sat,17,Dec,2011,21:57:49,PST,1324187869,54,1,11137972_824218614293587_1458071570_n.jpg,...,99.600000,2019-05-06 21:57:49,21,0,0,1,0,0,0,0
4343,Sat,17,Dec,2011,21:48:50,PST,1324187330,73,2,11176460_1421686131471918_2096745754_n.jpg,...,101.100000,2019-05-06 21:48:50,21,0,0,1,0,0,0,0
4344,Sat,17,Dec,2011,21:47:53,PST,1324187273,70,3,11176375_683535068417628_524087691_n.jpg,...,103.000000,2019-05-06 21:47:53,21,0,0,1,0,0,0,0
4345,Sat,17,Dec,2011,21:21:56,PST,1324185716,47,2,10809597_434355186730998_1387507161_n.jpg,...,108.400000,2019-05-06 21:21:56,21,0,0,1,0,0,0,0
4346,Sat,17,Dec,2011,21:07:05,PST,1324184825,189,2,11176499_863530597033456_399552263_n.jpg,...,99.400000,2019-05-06 21:07:05,21,0,0,1,0,0,0,0
4347,Sat,17,Dec,2011,19:57:23,PST,1324180643,58,1,11189913_1623845344518334_1746418078_n.jpg,...,103.100000,2019-05-06 19:57:23,19,0,0,1,0,0,0,0
4348,Sat,17,Dec,2011,19:44:31,PST,1324179871,86,2,11137736_913274155403050_1698221843_n.jpg,...,115.700000,2019-05-06 19:44:31,19,0,0,1,0,0,0,0
4349,Sat,17,Dec,2011,18:06:03,PST,1324173963,213,2,11190083_1591304184480100_1674495323_n.jpg,...,112.000000,2019-05-06 18:06:03,18,0,0,1,0,0,0,0
4350,Sat,17,Dec,2011,12:19:53,PST,1324153193,58,4,11190932_1678176412410195_1813298477_n.jpg,...,131.200000,2019-05-06 12:19:53,12,0,0,1,0,0,0,0
4351,Fri,16,Dec,2011,19:23:38,PST,1324092218,88,1,11123907_688751907917457_538791126_n.jpg,...,152.300000,2019-05-06 19:23:38,19,1,0,0,0,0,0,0
4352,Fri,16,Dec,2011,14:59:26,PST,1324076366,114,1,11137791_1575449399411254_297983060_n.jpg,...,158.600000,2019-05-06 14:59:26,14,1,0,0,0,0,0,0
4353,Fri,16,Dec,2011,02:24:28,PST,1324031068,88,2,11190963_571678359601970_173404930_n.jpg,...,209.400000,2019-05-06 02:24:28,2,1,0,0,0,0,0,0
4354,Fri,16,Dec,2011,02:19:21,PST,1324030761,89,3,11189965_645347785595719_583460329_n.jpg,...,211.800000,2019-05-06 02:19:21,2,1,0,0,0,0,0,0
4355,Thu,15,Dec,2011,22:51:39,PST,1324018299,101,2,11189712_810950768998418_235102544_n.jpg,...,212.500000,2019-05-06 22:51:39,22,0,0,0,0,1,0,0
4356,Thu,15,Dec,2011,22:43:19,PST,1324017799,99,1,11191407_1398698353786496_1609805602_n.jpg,...,222.400000,2019-05-06 22:43:19,22,0,0,0,0,1,0,0
4357,Thu,15,Dec,2011,22:42:49,PST,1324017769,95,2,11190746_468069006678841_1699145664_n.jpg,...,228.000000,2019-05-06 22:42:49,22,0,0,0,0,1,0,0
4358,Thu,15,Dec,2011,20:10:44,PST,1324008644,212,2,11116684_859918070749680_1150551678_n.jpg,...,221.100000,2019-05-06 20:10:44,20,0,0,0,0,1,0,0
4359,Thu,15,Dec,2011,20:00:15,PST,1324008015,176,1,11190258_1613682775542703_1599704532_n.jpg,...,267.800000,2019-05-06 20:00:15,20,0,0,0,0,1,0,0
4360,Thu,15,Dec,2011,13:45:55,PST,1323985555,250,3,11190820_353831731493515_2035264790_n.jpg,...,270.300000,2019-05-06 13:45:55,13,0,0,0,0,1,0,0
4361,Thu,15,Dec,2011,11:15:19,PST,1323976519,299,7,11187010_930252883663330_1298936190_n.jpg,...,289.600000,2019-05-06 11:15:19,11,0,0,0,0,1,0,0
4362,Thu,15,Dec,2011,07:27:35,PST,1323962855,177,6,11116637_414039015447515_905687688_n.jpg,...,302.111111,2019-05-06 07:27:35,7,0,0,0,0,1,0,0
4363,Thu,15,Dec,2011,06:46:20,PST,1323960380,596,15,11189781_737614569688666_77312608_n.jpg,...,265.375000,2019-05-06 06:46:20,6,0,0,0,0,1,0,0
4364,Wed,14,Dec,2011,10:55:08,PST,1323888908,113,3,11186886_955805781136832_979732000_n.jpg,...,287.142857,2019-05-06 10:55:08,10,0,0,0,0,0,0,1
4365,Tue,13,Dec,2011,15:50:57,PST,1323820257,108,1,11142305_654989777940064_1112311169_n.jpg,...,317.000000,2019-05-06 15:50:57,15,0,0,0,0,0,1,0
4366,Tue,13,Dec,2011,15:50:34,PST,1323820234,198,4,11176513_446654272166069_169035998_n.jpg,...,340.800000,2019-05-06 15:50:34,15,0,0,0,0,0,1,0
4367,Tue,13,Dec,2011,11:31:46,PST,1323804706,151,3,11137873_469711619844704_873437256_n.jpg,...,388.250000,2019-05-06 11:31:46,11,0,0,0,0,0,1,0
4368,Tue,13,Dec,2011,11:28:22,PST,1323804502,143,4,11186967_989005904484252_1563864266_n.jpg,...,470.000000,2019-05-06 11:28:22,11,0,0,0,0,0,1,0
4369,Tue,13,Dec,2011,10:56:22,PST,1323802582,643,15,11190343_1424987304484479_844740795_n.jpg,...,383.500000,2019-05-06 10:56:22,10,0,0,0,0,0,1,0
4370,Tue,13,Dec,2011,10:21:55,PST,1323800515,275,11,11191340_664443543683542_729019413_n.jpg,...,492.000000,2019-05-06 10:21:55,10,0,0,0,0,0,1,0
4371,Tue,13,Dec,2011,10:21:11,PST,1323800471,492,140,10369426_824721917608370_1839294297_n.jpg,...,0.000000,2019-05-06 10:21:11,10,0,0,0,0,0,1,0

In [24]:
X = new_AB_df.drop(['DOW', 'day', 'month', 'year', 'time', 'timezone', 'num_comments', 'name', 'num_likes', 'objects', 'datetime'], axis=1)

In [26]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
Y = new_AB_df.loc[:, 'num_likes']
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, shuffle = True, random_state=100)
LinearRegressionModel = linear_model.LinearRegression() 
LinearRegressionModel.fit(x_train, y_train)
print("Training: ", LinearRegressionModel.score(x_train, y_train))
print("Testing: ", LinearRegressionModel.score(x_test, y_test))

Training:  0.48740154920805645
Testing:  0.48700869589508966