In [1]:
import numpy as np 
import pandas as pd
import json
import time
from xgboost import XGBClassifier

In [2]:
image_DF = pd.read_csv('/Users/aceman/Desktop/alia_image_output.csv', names=['name', 'objects'])
image_DF

,name,objects
0,11282291_1609483835957378_809911312_n.jpg,[]
1,11311605_837138039673108_1517937451_n.jpg,['person']
2,13380946_1724689691105516_1322109584_n.jpg,[]
3,24327145_315946858882599_2981304668950364160_n...,"['person', 'person']"
4,13642984_1780551925499216_1607342993_n.jpg,"['person', 'bed']"
5,10661273_327291767432333_956551592_n.jpg,"['person', 'person']"
6,10009262_1412500712345975_170675753_n.jpg,"['person', 'person']"
7,11349199_1684215511793981_603032242_n.jpg,"['person', 'person']"
8,26180822_164660364264804_5976841042748506112_n...,['person']
9,14711850_1762254324024711_6695055537094000640_...,"['person', 'person', 'couch']"
10,15624171_716312811883810_1676858577861476352_n...,['person']
11,47693759_353966158771413_5679574953948691850_n...,"['person', 'person']"
12,13248942_1610186329309583_447340470_n.jpg,"['cat', 'cup']"
13,18161330_413446319041532_931646713662275584_n.jpg,"['person', 'cat']"
14,13385764_1022187937865899_1335377373_n.jpg,"['person', 'person', 'person', 'person', 'pers..."
15,1170053_629913930364936_613750233_n.jpg,['person']
16,12950261_962812583836430_1772881109_n.jpg,['person']
17,42800722_1104369806406123_1593482629301457003_...,[]
18,22637546_1639711502716370_5548510564273094656_...,['person']
19,32285013_2542173359341399_5977956097862926336_...,['person']
20,15251668_1612250249070052_1114004071498383360_...,['person']
21,54732168_565820340577066_4011507919684273063_n...,"['person', 'boat', 'person']"
22,12345968_1673056019576936_959012752_n.jpg,"['person', 'person']"
23,13167168_1103188066408758_1360017962_n.jpg,"['person', 'person', 'person', 'person', 'pers..."
24,51365294_984868081901197_5052970947162590759_n...,['person']
25,12599044_206081416409681_1712272819_n.jpg,"['person', 'car']"
26,11357636_850557211689625_630745782_n.jpg,"['person', 'person']"
27,12940094_1140324349342974_799480875_n.jpg,['person']
28,13249749_1059749127432661_1612996543_n.jpg,['person']
29,12826275_1576362406019355_1029999262_n.jpg,"['person', 'person']"
...,...,...
1201,16788733_1910889329144683_8918691824290234368_...,"['person', 'person', 'person', 'person', 'pers..."
1202,13694709_291002767924040_99962369_n.jpg,['person']
1203,21576572_130372094256096_3592170621850615808_n...,"['person', 'person']"
1204,52051215_393739254750192_538582212311073511_n.jpg,"['person', 'person', 'person']"
1205,36741603_406217799870996_2843266872483250176_n...,"['person', 'person', 'person', 'person']"
1206,13658790_1731636513752873_1076342341_n.jpg,"['person', 'person', 'person', 'person', 'pers..."
1207,12976395_1600858560232114_477067285_n.jpg,['person']
1208,14031599_1734714066783883_1863023247_n.jpg,"['person', 'car', 'car']"
1209,11085155_798674000180410_1805538976_n.jpg,"['person', 'tv', 'laptop']"
1210,10903532_733333903449430_778060420_n.jpg,"['person', 'person', 'person', 'person', 'pers..."
1211,15538265_175003342971951_1807991217967857664_n...,[]
1212,52860671_357916058146466_2519275098362140821_n...,"['person', 'person', 'person', 'person', 'pers..."
1213,18443209_1437915832920980_2830377533894033408_...,['person']
1214,17265738_111898456009414_3340255066064945152_n...,[]
1215,10986399_1572486246296637_1311635121_n.jpg,['person']
1216,26152433_917890928420153_540666469088755712_n.jpg,[]
1217,52467472_220618965455007_42936578590668622_n.jpg,"['potted plant', 'laptop']"
1218,15877283_1810558895823503_7143526818027405312_...,['person']
1219,11264266_386611988191976_1548474905_n.jpg,"['person', 'person', 'person', 'cup']"
1220,10986198_1083685908324383_719907916_n.jpg,"['person', 'person']"
1221,24845247_138993626747862_3491080599374921728_n...,['person']
1222,12145390_1525301991105133_1422393752_n.jpg,['person']
1223,13731121_533102086891617_1263639380_n.jpg,['bowl']
1224,17076380_1012962605502291_612643347806289920_n...,"['person', 'person', 'car', 'person', 'car', '..."
1225,55872715_386828002168769_5958953335350188970_n...,['person']
1226,26334552_162206197745757_8993206225520820224_n...,"['person', 'dog']"
1227,11370966_152397431768486_1807999522_n.jpg,"['person', 'person', 'person']"
1228,13266890_1636099136715621_741541421_n.jpg,"['person', 'person']"
1229,10513770_259910154212240_241528360_n.jpg,['person']
1230,53539955_2243629175854035_6615714782700747126_...,['person']

In [3]:
with open('aliaabhatt.json') as json_file:  
    AB_data = json.load(json_file)

In [4]:
data = [['DOW', 'day', 'month', 'year', 'time', 'timezone', 'epoch', 'num_likes', 'num_comments', 'url']]

In [5]:
for entry in AB_data['GraphImages']: 
    if entry['is_video'] == False:
        epoch = entry['taken_at_timestamp']
        t = time.strftime("%a, %d %b %Y %H:%M:%S %Z", time.localtime(epoch))
        row = t.split(' ')
        row[0] = row[0][:len(row[0])-1]
        row.append(epoch)
        row.append(entry['edge_media_preview_like']['count'])
        row.append(entry['edge_media_to_comment']['count'])
        temp_url = entry['display_url'].split('.jpg')[0].split('/')[8] + '.jpg'
        row.append(temp_url)
        data.append(row)

In [6]:
AB_df = pd.DataFrame(data, columns=['DOW', 'day', 'month', 'year', 'time', 'timezone', 'epoch', 'num_likes', 'num_comments', 'url'])
AB_df = AB_df.drop([0])

In [7]:
AB_df.head()

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,url
1,Tue,09,Apr,2019,22:41:49,PDT,1554874909,1407205,5045,54511586_1301069350049619_3770365202227246635_...
2,Tue,09,Apr,2019,05:34:04,PDT,1554813244,1364181,5621,54513633_2132051633558147_5634581464208102191_...
3,Tue,09,Apr,2019,05:23:41,PDT,1554812621,1629505,6615,56576043_388197402035165_3768893677250277139_n...
4,Mon,08,Apr,2019,23:24:01,PDT,1554791041,758278,1549,54446621_164522324545815_2144201445962359739_n...
5,Mon,08,Apr,2019,09:35:13,PDT,1554741313,1132241,3289,56315761_1233235843506462_5516913578636583739_...

In [8]:
new_AB_df = AB_df.merge(image_DF, how='inner', left_on='url', right_on='name')
new_AB_df = new_AB_df.drop(columns=['url'])
text_file = open("yolov3.txt", "r")
lines = text_file.read().split()

In [9]:
for item in lines:
    temp_item = []
    for i in new_AB_df['objects']:
        count = i.count(item)
        if count > 0:
            temp_item.append(1)
        else:
            temp_item.append(0)
    category = 'is_' + item
    new_AB_df[category] = temp_item
    
new_AB_df.head()

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,name,...,is_sink,is_refrigerator,is_book,is_clock,is_vase,is_scissors,is_teddy,is_hair,is_drier,is_toothbrush
0,Tue,09,Apr,2019,22:41:49,PDT,1554874909,1407205,5045,54511586_1301069350049619_3770365202227246635_...,...,0,0,0,0,0,0,0,0,0,0
1,Tue,09,Apr,2019,05:34:04,PDT,1554813244,1364181,5621,54513633_2132051633558147_5634581464208102191_...,...,0,0,0,0,0,0,0,0,0,0
2,Tue,09,Apr,2019,05:23:41,PDT,1554812621,1629505,6615,56576043_388197402035165_3768893677250277139_n...,...,0,0,0,0,0,0,0,0,0,0
3,Mon,08,Apr,2019,23:24:01,PDT,1554791041,758278,1549,54446621_164522324545815_2144201445962359739_n...,...,0,0,0,0,0,0,0,0,0,0
4,Mon,08,Apr,2019,09:35:13,PDT,1554741313,1132241,3289,56315761_1233235843506462_5516913578636583739_...,...,0,0,0,0,0,0,0,0,0,0

In [10]:
curr_index = 1
previous_likes = np.array([])
while (curr_index <= len(new_AB_df)):
    end_index = min(len(new_AB_df) + 1, curr_index + 10)
    previous_likes = np.append(previous_likes, new_AB_df['num_likes'][curr_index:end_index].mean())
    curr_index=curr_index + 1
    
previous_likes[len(new_AB_df) - 1] = 0
new_AB_df['previous_likes'] = previous_likes

In [11]:
new_AB_df.head()

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,name,...,is_refrigerator,is_book,is_clock,is_vase,is_scissors,is_teddy,is_hair,is_drier,is_toothbrush,previous_likes
0,Tue,09,Apr,2019,22:41:49,PDT,1554874909,1407205,5045,54511586_1301069350049619_3770365202227246635_...,...,0,0,0,0,0,0,0,0,0,1316811.7
1,Tue,09,Apr,2019,05:34:04,PDT,1554813244,1364181,5621,54513633_2132051633558147_5634581464208102191_...,...,0,0,0,0,0,0,0,0,0,1380822.2
2,Tue,09,Apr,2019,05:23:41,PDT,1554812621,1629505,6615,56576043_388197402035165_3768893677250277139_n...,...,0,0,0,0,0,0,0,0,0,1366938.5
3,Mon,08,Apr,2019,23:24:01,PDT,1554791041,758278,1549,54446621_164522324545815_2144201445962359739_n...,...,0,0,0,0,0,0,0,0,0,1346500.1
4,Mon,08,Apr,2019,09:35:13,PDT,1554741313,1132241,3289,56315761_1233235843506462_5516913578636583739_...,...,0,0,0,0,0,0,0,0,0,1339493.6

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
avg_likes = new_AB_df['num_likes'].mean()

In [14]:
new_AB_df['datetime'] = pd.to_datetime(new_AB_df['time'])
new_AB_df['hour'] = [i.hour for i in new_AB_df['datetime']]

In [15]:
AB_df.shape[0]

1253

In [16]:
days = pd.get_dummies(new_AB_df['DOW'])

In [17]:
months = pd.get_dummies(new_AB_df['month'])

In [18]:
new_AB_df = new_AB_df.merge(days, left_index = True, right_index = True)

In [19]:
new_AB_df = new_AB_df.dropna()
new_AB_df.loc[:, (new_AB_df != 0).any(axis=0)]

,DOW,day,month,year,time,timezone,epoch,num_likes,num_comments,name,...,previous_likes,datetime,hour,Fri,Mon,Sat,Sun,Thu,Tue,Wed
0,Tue,09,Apr,2019,22:41:49,PDT,1554874909,1407205,5045,54511586_1301069350049619_3770365202227246635_...,...,1.316812e+06,2019-05-05 22:41:49,22,0,0,0,0,0,1,0
1,Tue,09,Apr,2019,05:34:04,PDT,1554813244,1364181,5621,54513633_2132051633558147_5634581464208102191_...,...,1.380822e+06,2019-05-05 05:34:04,5,0,0,0,0,0,1,0
2,Tue,09,Apr,2019,05:23:41,PDT,1554812621,1629505,6615,56576043_388197402035165_3768893677250277139_n...,...,1.366938e+06,2019-05-05 05:23:41,5,0,0,0,0,0,1,0
3,Mon,08,Apr,2019,23:24:01,PDT,1554791041,758278,1549,54446621_164522324545815_2144201445962359739_n...,...,1.346500e+06,2019-05-05 23:24:01,23,0,1,0,0,0,0,0
4,Mon,08,Apr,2019,09:35:13,PDT,1554741313,1132241,3289,56315761_1233235843506462_5516913578636583739_...,...,1.339494e+06,2019-05-05 09:35:13,9,0,1,0,0,0,0,0
5,Sun,07,Apr,2019,19:59:38,PDT,1554692378,941128,2241,54247609_230606107811995_7277821849700788693_n...,...,1.335971e+06,2019-05-05 19:59:38,19,0,0,0,1,0,0,0
6,Sun,07,Apr,2019,08:11:20,PDT,1554649880,1579571,4425,57156375_361870571401839_8525508616934346362_n...,...,1.295891e+06,2019-05-05 08:11:20,8,0,0,0,1,0,0,0
7,Sun,07,Apr,2019,08:09:22,PDT,1554649762,1660257,7244,54512753_179575526364893_8758593351656993062_n...,...,1.179568e+06,2019-05-05 08:09:22,8,0,0,0,1,0,0,0
8,Sun,07,Apr,2019,08:07:08,PDT,1554649628,1320718,4604,56165224_426676758141883_4382006928037211232_n...,...,1.169129e+06,2019-05-05 08:07:08,8,0,0,0,1,0,0,0
9,Sat,06,Apr,2019,10:26:18,PDT,1554571578,1327399,4866,53930301_319372985347870_8365750599461788749_n...,...,1.123559e+06,2019-05-05 10:26:18,10,0,0,1,0,0,0,0
10,Sat,06,Apr,2019,09:14:30,PDT,1554567270,1454839,6395,54277691_599738137105133_6822634084568678508_n...,...,1.096379e+06,2019-05-05 09:14:30,9,0,0,1,0,0,0,0
11,Fri,05,Apr,2019,04:30:35,PDT,1554463835,2004286,11399,54511197_2819194811639497_698595712988972714_n...,...,9.586970e+05,2019-05-05 04:30:35,4,1,0,0,0,0,0,0
12,Thu,04,Apr,2019,00:28:12,PDT,1554362892,1490668,7319,55842831_331482087720618_1256000907256194362_n...,...,8.744036e+05,2019-05-05 00:28:12,0,0,0,0,0,1,0,0
13,Wed,03,Apr,2019,03:36:13,PDT,1554287773,553894,2439,54511025_778197322580169_294373103551428885_n.jpg,...,8.929144e+05,2019-05-05 03:36:13,3,0,0,0,0,0,0,1
14,Tue,02,Apr,2019,08:15:01,PDT,1554218101,1062176,3895,52147140_271968407044647_1474082019395639928_n...,...,9.335801e+05,2019-05-05 08:15:01,8,0,0,0,0,0,1,0
15,Tue,02,Apr,2019,06:24:18,PDT,1554211458,905900,3655,55886208_657889447993528_3716811617881679737_n...,...,1.035227e+06,2019-05-05 06:24:18,6,0,0,0,0,0,1,0
16,Tue,02,Apr,2019,06:20:51,PDT,1554211251,1178776,4754,54247701_410383799791935_6035561318606054754_n...,...,1.032744e+06,2019-05-05 06:20:51,6,0,0,0,0,0,1,0
17,Sat,30,Mar,2019,02:39:06,PDT,1553938746,497029,1711,54277668_482963215573944_2173894151686744750_n...,...,1.062565e+06,2019-05-05 02:39:06,2,0,0,1,0,0,0,0
18,Thu,28,Mar,2019,22:30:19,PDT,1553837419,1216320,5597,53871686_311004832944447_7687294829506514012_n...,...,1.123059e+06,2019-05-05 22:30:19,22,0,0,0,0,1,0,0
19,Thu,28,Mar,2019,21:24:28,PDT,1553833468,871703,3322,54511194_316042602429112_4909322531097362425_n...,...,1.187616e+06,2019-05-05 21:24:28,21,0,0,0,0,1,0,0
20,Thu,28,Mar,2019,19:26:02,PDT,1553826362,1183041,5355,54447042_289980058570061_5517793563561985451_n...,...,1.203033e+06,2019-05-05 19:26:02,19,0,0,0,0,1,0,0
21,Thu,28,Mar,2019,06:45:29,PDT,1553780729,627463,1390,54446573_2310589115866933_4157977642861165727_...,...,1.191677e+06,2019-05-05 06:45:29,6,0,0,0,0,1,0,0
22,Thu,28,Mar,2019,02:23:04,PDT,1553764984,647734,2245,53230832_339692293346329_3605980157659452530_n...,...,1.182870e+06,2019-05-05 02:23:04,2,0,0,0,0,1,0,0
23,Thu,28,Mar,2019,02:21:52,PDT,1553764912,739002,1366,53859476_669804643422572_4755845080822706387_n...,...,1.240708e+06,2019-05-05 02:21:52,2,0,0,0,0,1,0,0
24,Wed,27,Mar,2019,23:16:22,PDT,1553753782,1468833,3541,52508199_326205071368058_2026571243528074254_n...,...,1.154290e+06,2019-05-05 23:16:22,23,0,0,0,0,0,0,1
25,Sun,24,Mar,2019,01:45:21,PDT,1553417121,1922368,11310,53539955_2243629175854035_6615714782700747126_...,...,1.156245e+06,2019-05-05 01:45:21,1,0,0,0,1,0,0,0
26,Sun,24,Mar,2019,01:36:47,PDT,1553416607,1153948,5156,53593536_1232438640249146_7997848900207188360_...,...,1.184380e+06,2019-05-05 01:36:47,1,0,0,0,1,0,0,0
27,Thu,21,Mar,2019,22:31:44,PDT,1553232704,795241,1370,52434290_332790387581567_7110273072429596339_n...,...,1.240633e+06,2019-05-05 22:31:44,22,0,0,0,0,1,0,0
28,Wed,20,Mar,2019,00:39:49,PDT,1553067589,1821256,8336,54277573_125346315248846_1134657028396474666_n...,...,1.147255e+06,2019-05-05 00:39:49,0,0,0,0,0,0,0,1
29,Tue,19,Mar,2019,02:55:21,PDT,1552989321,1517275,8042,53551273_435309623874511_6842093722954797916_n...,...,1.212533e+06,2019-05-05 02:55:21,2,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1153,Sat,04,May,2013,07:44:09,PDT,1367678649,7351,71,11349199_804002019682533_510425822_n.jpg,...,9.650000e+03,2019-05-05 07:44:09,7,0,0,1,0,0,0,0
1154,Sat,27,Apr,2013,12:59:34,PDT,1367092774,12872,134,11248966_678972815542104_1290291726_n.jpg,...,8.965600e+03,2019-05-05 12:59:34,12,0,0,1,0,0,0,0
1155,Fri,05,Apr,2013,23:05:04,PDT,1365228304,7003,78,11252887_876472202440761_380813150_n.jpg,...,9.278400e+03,2019-05-05 23:05:04,23,1,0,0,0,0,0,0
1156,Thu,04,Apr,2013,10:00:19,PDT,1365094819,18507,487,11330669_1588680764736459_1745920290_n.jpg,...,8.540700e+03,2019-05-05 10:00:19,10,0,0,0,0,1,0,0
1157,Tue,02,Apr,2013,03:03:30,PDT,1364897010,5699,51,11312154_470264689788855_917966161_n.jpg,...,9.090600e+03,2019-05-05 03:03:30,3,0,0,0,0,0,1,0
1158,Sat,23,Mar,2013,07:04:23,PDT,1364047463,5213,61,11255231_676575512471133_1307593578_n.jpg,...,9.257000e+03,2019-05-05 07:04:23,7,0,0,1,0,0,0,0
1159,Wed,20,Mar,2013,08:09:50,PDT,1363792190,12498,278,11264266_386611988191976_1548474905_n.jpg,...,8.692200e+03,2019-05-05 08:09:50,8,0,0,0,0,0,0,1
1160,Thu,14,Mar,2013,11:04:54,PDT,1363284294,8333,124,11263256_1582777781980296_1429264106_n.jpg,...,8.980000e+03,2019-05-05 11:04:54,11,0,0,0,0,1,0,0
1161,Thu,07,Mar,2013,21:21:20,PST,1362720080,14613,284,11311605_837138039673108_1517937451_n.jpg,...,8.820600e+03,2019-05-05 21:21:20,21,0,0,0,0,1,0,0
1162,Thu,07,Mar,2013,21:16:57,PST,1362719817,5381,38,11282582_1579782332303345_994481462_n.jpg,...,9.594400e+03,2019-05-05 21:16:57,21,0,0,0,0,1,0,0
1163,Wed,20,Feb,2013,07:35:32,PST,1361374532,6381,55,11232509_1394638434197153_1128158918_n.jpg,...,1.008730e+04,2019-05-05 07:35:32,7,0,0,0,0,0,0,1
1164,Sat,16,Feb,2013,08:02:07,PST,1361030527,6028,45,11272459_473307772844753_1489527667_n.jpg,...,1.051310e+04,2019-05-05 08:02:07,8,0,0,1,0,0,0,0
1165,Thu,14,Feb,2013,12:57:39,PST,1360875459,10131,146,11288198_465149576982855_97148581_n.jpg,...,1.070360e+04,2019-05-05 12:57:39,12,0,0,0,0,1,0,0
1166,Sat,09,Feb,2013,08:23:42,PST,1360427022,11130,245,11256286_1396150537378542_79863073_n.jpg,...,1.038010e+04,2019-05-05 08:23:42,8,0,0,1,0,0,0,0
1167,Tue,29,Jan,2013,06:54:11,PST,1359471251,11198,172,11242289_841120512590147_242213731_n.jpg,...,1.022950e+04,2019-05-05 06:54:11,6,0,0,0,0,0,1,0
1168,Mon,07,Jan,2013,04:58:16,PST,1357563496,6877,79,11232667_1601539620097303_2011971244_n.jpg,...,1.052310e+04,2019-05-05 04:58:16,4,0,1,0,0,0,0,0
1169,Fri,04,Jan,2013,06:29:14,PST,1357309754,6850,57,11246761_484906318351622_1213115149_n.jpg,...,1.260250e+04,2019-05-05 06:29:14,6,1,0,0,0,0,0,0
1170,Tue,01,Jan,2013,05:06:54,PST,1357045614,11211,119,11232776_663075050504183_400473037_n.jpg,...,1.352210e+04,2019-05-05 05:06:54,5,0,0,0,0,0,1,0
1171,Sun,30,Dec,2012,12:44:05,PST,1356900245,13019,230,11236365_1639220822976087_1432900327_n.jpg,...,1.683480e+04,2019-05-05 12:44:05,12,0,0,0,1,0,0,0
1172,Sat,29,Dec,2012,23:20:25,PST,1356852025,13119,191,11258534_1408598776130142_277036896_n.jpg,...,1.677810e+04,2019-05-05 23:20:25,23,0,0,1,0,0,0,0
1173,Wed,26,Dec,2012,06:37:55,PST,1356532675,11310,111,11258277_639535932843000_1701787239_n.jpg,...,1.738567e+04,2019-05-05 06:37:55,6,0,0,0,0,0,0,1
1174,Tue,25,Dec,2012,07:55:05,PST,1356450905,10286,87,11259273_1621062548107231_294094964_n.jpg,...,1.827312e+04,2019-05-05 07:55:05,7,0,0,0,0,0,1,0
1175,Mon,24,Dec,2012,11:11:24,PST,1356376284,12036,149,11254125_447620772078874_1340922488_n.jpg,...,1.916414e+04,2019-05-05 11:11:24,11,0,1,0,0,0,0,0
1176,Sun,23,Dec,2012,06:08:13,PST,1356271693,7895,90,11202537_844699565619163_871377142_n.jpg,...,2.104233e+04,2019-05-05 06:08:13,6,0,0,0,1,0,0,0
1177,Fri,14,Dec,2012,21:55:34,PST,1355550934,9692,143,11265920_583997095074644_551639458_n.jpg,...,2.331240e+04,2019-05-05 21:55:34,21,1,0,0,0,0,0,0
1178,Thu,13,Dec,2012,20:17:52,PST,1355458672,9813,100,11236212_1582719132009601_357976372_n.jpg,...,2.668725e+04,2019-05-05 20:17:52,20,0,0,0,0,1,0,0
1179,Fri,07,Dec,2012,11:44:25,PST,1354909465,27644,286,11255722_1141321789227149_1990340728_n.jpg,...,2.636833e+04,2019-05-05 11:44:25,11,1,0,0,0,0,0,0
1180,Mon,03,Dec,2012,05:33:06,PST,1354541586,20407,257,11236290_1403258363332290_1781177012_n.jpg,...,2.934900e+04,2019-05-05 05:33:06,5,0,1,0,0,0,0,0
1181,Sat,01,Dec,2012,04:40:45,PST,1354365645,46146,873,11242410_1435730440062271_642341433_n.jpg,...,1.255200e+04,2019-05-05 04:40:45,4,0,0,1,0,0,0,0
1182,Wed,28,Nov,2012,13:44:07,PST,1354139047,12552,220,11235851_1624376831140050_398025253_n.jpg,...,0.000000e+00,2019-05-05 13:44:07,13,0,0,0,0,0,0,1

In [20]:
X = new_AB_df.drop(['DOW', 'day', 'month', 'year', 'time', 'timezone', 'num_comments', 'name', 'num_likes', 'objects', 'datetime'], axis=1)
print(X.columns)

Index(['epoch', 'is_person', 'is_bicycle', 'is_car', 'is_motorcycle',
       'is_airplane', 'is_bus', 'is_train', 'is_truck', 'is_boat',
       ...
       'is_toothbrush', 'previous_likes', 'hour', 'Fri', 'Mon', 'Sat', 'Sun',
       'Thu', 'Tue', 'Wed'],
      dtype='object', length=102)

In [21]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
print(X)
Y = new_AB_df.loc[:, 'num_likes']
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, shuffle = True, random_state=100)
LinearRegressionModel = linear_model.LinearRegression() 
LinearRegressionModel.fit(x_train, y_train)
print("Training: ", LinearRegressionModel.score(x_train, y_train))
print("Testing: ", LinearRegressionModel.score(x_test, y_test))

           epoch  is_person  is_bicycle  is_car  is_motorcycle  is_airplane  \
0     1554874909          1           0       0              0            0
1     1554813244          1           0       0              0            0
2     1554812621          1           0       0              0            0
3     1554791041          1           0       0              0            0
4     1554741313          1           0       0              0            0
5     1554692378          1           0       0              0            0
6     1554649880          1           0       0              0            0
7     1554649762          1           0       0              0            0
8     1554649628          1           0       0              0            0
9     1554571578          1           0       0              0            0
10    1554567270          1           0       0              0            0
11    1554463835          1           0       0              0            0
12    1554362892          1           0       0              0            0
13    1554287773          1           0       0              0            0
14    1554218101          1           0       0              0            0
15    1554211458          1           0       0              0            0
16    1554211251          1           0       0              0            0
17    1553938746          1           0       0              0            0
18    1553837419          1           0       0              0            0
19    1553833468          1           0       0              0            0
20    1553826362          1           0       0              0            0
21    1553780729          1           0       0              0            0
22    1553764984          1           0       0              0            0
23    1553764912          1           0       0              0            0
24    1553753782          1           0       0              0            0
25    1553417121          1           0       0              0            0
26    1553416607          1           0       0              0            0
27    1553232704          1           0       0              0            0
28    1553067589          1           0       0              0            0
29    1552989321          1           0       0              0            0
...          ...        ...         ...     ...            ...          ...
1153  1367678649          1           0       0              0            0
1154  1367092774          1           0       0              0            0
1155  1365228304          0           0       0              0            0
1156  1365094819          1           0       0              0            0
1157  1364897010          0           0       0              0            0
1158  1364047463          0           0       0              0            0
1159  1363792190          1           0       0              0            0
1160  1363284294          0           0       0              0            0
1161  1362720080          1           0       0              0            0
1162  1362719817          0           0       0              0            0
1163  1361374532          0           0       0              0            0
1164  1361030527          0           0       0              0            0
1165  1360875459          1           0       0              0            0
1166  1360427022          1           0       0              0            0
1167  1359471251          1           0       0              0            0
1168  1357563496          0           0       0              0            0
1169  1357309754          0           0       0              0            0
1170  1357045614          1           0       0              0            0
1171  1356900245          0           0       0              0            0
1172  1356852025          1           0       0              0            0
1173  1356532675          1           0       0              0            0
1174  1356450905          1           0       0              0            0
1175  1356376284          1           0       0              0            0
1176  1356271693          0           0       0              0            0
1177  1355550934          0           0       0              0            0
1178  1355458672          0           0       0              0            0
1179  1354909465          1           0       0              0            0
1180  1354541586          1           0       0              0            0
1181  1354365645          1           0       0              0            0
1182  1354139047          0           0       0              0            0

      is_bus  is_train  is_truck  is_boat ...   is_toothbrush  previous_likes  \
0          0         0         0        0 ...               0    1.316812e+06
1          0         0         0        0 ...               0    1.380822e+06
2          0         0         0        0 ...               0    1.366938e+06
3          0         0         0        0 ...               0    1.346500e+06
4          0         0         0        0 ...               0    1.339494e+06
5          0         0         0        0 ...               0    1.335971e+06
6          0         0         0        0 ...               0    1.295891e+06
7          0         0         0        0 ...               0    1.179568e+06
8          0         0         0        0 ...               0    1.169129e+06
9          0         0         0        0 ...               0    1.123559e+06
10         0         0         0        0 ...               0    1.096379e+06
11         0         0         0        0 ...               0    9.586970e+05
12         0         0         0        0 ...               0    8.744036e+05
13         0         0         0        0 ...               0    8.929144e+05
14         0         0         0        0 ...               0    9.335801e+05
15         0         0         0        0 ...               0    1.035227e+06
16         0         0         0        0 ...               0    1.032744e+06
17         0         0         0        0 ...               0    1.062565e+06
18         0         0         0        0 ...               0    1.123059e+06
19         0         0         0        0 ...               0    1.187616e+06
20         0         0         0        0 ...               0    1.203033e+06
21         0         0         0        0 ...               0    1.191677e+06
22         0         0         0        0 ...               0    1.182870e+06
23         0         0         0        0 ...               0    1.240708e+06
24         0         0         0        1 ...               0    1.154290e+06
25         0         0         0        0 ...               0    1.156245e+06
26         0         0         0        0 ...               0    1.184380e+06
27         0         0         0        0 ...               0    1.240633e+06
28         0         0         0        0 ...               0    1.147255e+06
29         0         0         0        0 ...               0    1.212533e+06
...      ...       ...       ...      ... ...             ...             ...
1153       0         0         0        0 ...               0    9.650000e+03
1154       0         0         0        0 ...               0    8.965600e+03
1155       0         0         0        0 ...               0    9.278400e+03
1156       0         0         0        0 ...               0    8.540700e+03
1157       0         0         0        0 ...               0    9.090600e+03
1158       0         0         0        0 ...               0    9.257000e+03
1159       0         0         0        0 ...               0    8.692200e+03
1160       0         0         0        0 ...               0    8.980000e+03
1161       0         0         0        0 ...               0    8.820600e+03
1162       0         0         0        0 ...               0    9.594400e+03
1163       0         0         0        0 ...               0    1.008730e+04
1164       0         0         0        0 ...               0    1.051310e+04
1165       0         0         0        0 ...               0    1.070360e+04
1166       0         0         0        0 ...               0    1.038010e+04
1167       0         0         0        0 ...               0    1.022950e+04
1168       0         0         0        0 ...               0    1.052310e+04
1169       0         0         0        0 ...               0    1.260250e+04
1170       0         0         0        0 ...               0    1.352210e+04
1171       0         0         0        0 ...               0    1.683480e+04
1172       0         0         0        0 ...               0    1.677810e+04
1173       0         0         0        0 ...               0    1.738567e+04
1174       0         0         0        0 ...               0    1.827312e+04
1175       0         0         0        0 ...               0    1.916414e+04
1176       0         0         0        0 ...               0    2.104233e+04
1177       0         0         0        0 ...               0    2.331240e+04
1178       0         0         0        0 ...               0    2.668725e+04
1179       0         0         0        0 ...               0    2.636833e+04
1180       0         0         0        0 ...               0    2.934900e+04
1181       0         0         0        0 ...               0    1.255200e+04
1182       0         0         0        0 ...               0    0.000000e+00

      hour  Fri  Mon  Sat  Sun  Thu  Tue  Wed
0       22    0    0    0    0    0    1    0
1        5    0    0    0    0    0    1    0
2        5    0    0    0    0    0    1    0
3       23    0    1    0    0    0    0    0
4        9    0    1    0    0    0    0    0
5       19    0    0    0    1    0    0    0
6        8    0    0    0    1    0    0    0
7        8    0    0    0    1    0    0    0
8        8    0    0    0    1    0    0    0
9       10    0    0    1    0    0    0    0
10       9    0    0    1    0    0    0    0
11       4    1    0    0    0    0    0    0
12       0    0    0    0    0    1    0    0
13       3    0    0    0    0    0    0    1
14       8    0    0    0    0    0    1    0
15       6    0    0    0    0    0    1    0
16       6    0    0    0    0    0    1    0
17       2    0    0    1    0    0    0    0
18      22    0    0    0    0    1    0    0
19      21    0    0    0    0    1    0    0
20      19    0    0    0    0    1    0    0
21       6    0    0    0    0    1    0    0
22       2    0    0    0    0    1    0    0
23       2    0    0    0    0    1    0    0
24      23    0    0    0    0    0    0    1
25       1    0    0    0    1    0    0    0
26       1    0    0    0    1    0    0    0
27      22    0    0    0    0    1    0    0
28       0    0    0    0    0    0    0    1
29       2    0    0    0    0    0    1    0
...    ...  ...  ...  ...  ...  ...  ...  ...
1153     7    0    0    1    0    0    0    0
1154    12    0    0    1    0    0    0    0
1155    23    1    0    0    0    0    0    0
1156    10    0    0    0    0    1    0    0
1157     3    0    0    0    0    0    1    0
1158     7    0    0    1    0    0    0    0
1159     8    0    0    0    0    0    0    1
1160    11    0    0    0    0    1    0    0
1161    21    0    0    0    0    1    0    0
1162    21    0    0    0    0    1    0    0
1163     7    0    0    0    0    0    0    1
1164     8    0    0    1    0    0    0    0
1165    12    0    0    0    0    1    0    0
1166     8    0    0    1    0    0    0    0
1167     6    0    0    0    0    0    1    0
1168     4    0    1    0    0    0    0    0
1169     6    1    0    0    0    0    0    0
1170     5    0    0    0    0    0    1    0
1171    12    0    0    0    1    0    0    0
1172    23    0    0    1    0    0    0    0
1173     6    0    0    0    0    0    0    1
1174     7    0    0    0    0    0    1    0
1175    11    0    1    0    0    0    0    0
1176     6    0    0    0    1    0    0    0
1177    21    1    0    0    0    0    0    0
1178    20    0    0    0    0    1    0    0
1179    11    1    0    0    0    0    0    0
1180     5    0    1    0    0    0    0    0
1181     4    0    0    1    0    0    0    0
1182    13    0    0    0    0    0    0    1

[1183 rows x 102 columns]
Training:  0.8067084498135582
Testing:  0.8479728825030497